const CH3_DATA = {
  "title": "Lernfeld 3: Clients und Netzwerke",
  "priority": 3,
  "subsections": [
    {
      "title": "Hardware und Schnittstellen",
      "id": "hardware",
      "description": "CPU, RAM, Mainboard, Schnittstellen (USB-C, HDMI), HDD/SSD, USV, Drucker.",
      "priority": "sehr hoch",
      "questions": [
        { "question": "Welche Komponente wird als 'Gehirn' des Computers bezeichnet?", "options": ["RAM", "CPU", "Mainboard", "GPU"], "answer": 1 },
        { "question": "Welcher RAM-Typ ist aktuell der Standard für moderne PCs (2024)?", "options": ["DDR3", "DDR4", "DDR5", "SDRAM"], "answer": 2 },
        { "question": "Was ist der Vorteil einer NVMe-SSD gegenüber einer SATA-SSD?", "options": ["Höhere Datenübertragungsraten (PCIe)", "Geringerer Preis", "Mehr Speicherplatz", "Sie ist größer"], "answer": 0 },
        { "question": "Welche Schnittstelle unterstützt Daten, Video und Strom (Power Delivery) gleichzeitig?", "options": ["VGA", "HDMI", "USB-C / Thunderbolt", "DVI"], "answer": 2 },
        { "question": "Wofür steht die Abkürzung 'USV'?", "options": ["Universal Serial Video", "Unterbrechungsfreie Stromversorgung", "Unit System Version", "User Security Vault"], "answer": 1 },
        { "question": "Welcher USV-Typ bietet den höchsten Schutz (Online-USV)?", "options": ["VFD (Offline)", "VI (Line-Interactive)", "VFI (Double Conversion)", "Hybrid"], "answer": 2 },
        { "question": "Was beschreibt der Formfaktor 'ATX'?", "options": ["Eine CPU-Architektur", "Die Größe und Bohrungen eines Mainboards", "Ein Festplatten-Protokoll", "Eine Monitorauflösung"], "answer": 1 },
        { "question": "Was ist der Unterschied zwischen einem Laser- und einem Tintenstrahldrucker?", "options": ["Laser nutzt Toner, Tinte nutzt flüssige Farbe", "Tinte ist immer schneller", "Laser ist nur für Fotos", "Tinte braucht keine Wartung"], "answer": 0 },
        { "question": "Was ist der 'Sockel' auf einem Mainboard?", "options": ["Die Halterung für die CPU", "Der Anschluss für das Netzteil", "Ein Steckplatz für RAM", "Die Batteriehalterung"], "answer": 0 },
        { "question": "Was ist 'ECC-RAM'?", "options": ["Besonders schneller RAM", "RAM mit Fehlerkorrektur (Error Correction Code)", "Günstiger RAM für Laptops", "RAM für Grafikkarten"], "answer": 1 },
        { "question": "Was bedeutet 'Plug and Play'?", "options": ["Hardware wird automatisch erkannt und konfiguriert", "Man muss alles manuell löten", "Hardware funktioniert nur beim Spielen", "Stecker ziehen und wegwerfen"], "answer": 0 },
        { "question": "Wofür wird 'Thunderbolt 4' hauptsächlich genutzt?", "options": ["Stromversorgung von Staubsaugern", "Hochgeschwindigkeits-Datentransfer und Video", "Nur zum Laden von Handys", "Interne Festplattenverbindung"], "answer": 1 },
        { "question": "Was ist ein 'Chipsatz'?", "options": ["Eine Tüte Chips für den Admin", "Steuereinheit auf dem Mainboard für Datenfluss", "Der Lüfter auf der CPU", "Die BIOS-Software"], "answer": 1 },
        { "question": "Was ist der Vorteil von OLED-Displays?", "options": ["Echter Schwarzwert durch selbstleuchtende Pixel", "Immer billiger als LCD", "Verbrauchen immer mehr Strom", "Geringere Lebensdauer ist ein Feature"], "answer": 0 },
        { "question": "Was ist 'Hyper-Threading'?", "options": ["Mehrere virtuelle Kerne pro physischem CPU-Kern", "Zwei CPUs auf einem Board", "Besonders schneller Internetzugang", "Ein Virus"], "answer": 0 },
        { "question": "Welche Einheit gibt die Kapazität einer USV oft an?", "options": ["VA (Volt-Ampere)", "Hz (Hertz)", "dpi (Dots per inch)", "Mbps"], "answer": 0 },
        { "question": "Was ist der 'Budge-Effekt' bei Druckern (TCO)?", "options": ["Günstiger Anschaffungspreis, teures Verbrauchsmaterial", "Hoher Preis, geringe Qualität", "Drucker wird immer schwerer", "Kein Effekt bekannt"], "answer": 0 },
        { "question": "Was ist 'SATA'?", "options": ["Ein Protokoll für Massenspeicher", "Ein Betriebssystem", "Eine Programmiersprache", "Ein Netzwerkstandard"], "answer": 0 },
        { "question": "Was macht die 'Northbridge' (klassisch)?", "options": ["Verbindung CPU zu RAM und Grafik", "Verbindung zu USB und Audio", "Stromversorgung", "Netzwerksteuerung"], "answer": 0 },
        { "question": "Was ist ein 'BIOS / UEFI'?", "options": ["Firmware zum Booten des Systems", "Ein Texteditor", "Ein Antivirenprogramm", "Die Benutzeroberfläche von Windows"], "answer": 0 }
      ]
    },
    {
      "title": "Netzwerktechnik (IPv4/v6)",
      "id": "netzwerk",
      "description": "OSI-Modell, Subnetting, Adressaufbau, Komponenten (Switch, Router).",
      "priority": "sehr hoch",
      "questions": [
        { "question": "Auf welcher OSI-Schicht arbeitet ein Layer-2-Switch?", "options": ["Schicht 1 (Physical)", "Schicht 2 (Data Link)", "Schicht 3 (Network)", "Schicht 4 (Transport)"], "answer": 1 },
        { "question": "Wie viele Bits hat eine IPv4-Adresse?", "options": ["16", "32", "64", "128"], "answer": 1 },
        { "question": "Was ist die Broadcast-Adresse im Netz 192.168.1.0/24?", "options": ["192.168.1.1", "192.168.1.254", "192.168.1.255", "192.168.1.0"], "answer": 2 },
        { "question": "Welches Protokoll ordnet IP-Adressen MAC-Adressen zu?", "options": ["DHCP", "DNS", "ARP", "ICMP"], "answer": 2 },
        { "question": "Wie lang ist eine IPv6-Adresse?", "options": ["32 Bit", "64 Bit", "128 Bit", "256 Bit"], "answer": 2 },
        { "question": "Was ist 'SLAAC' bei IPv6?", "options": ["Stateless Address Autoconfiguration", "Ein spezielles Kabel", "Sicherheits-Layer", "Server Load Balancing"], "answer": 0 },
        { "question": "Welches OSI-Layer ist für das Routing zuständig?", "options": ["Schicht 2", "Schicht 3", "Schicht 4", "Schicht 7"], "answer": 1 },
        { "question": "Was ist eine 'Subnetzmaske'?", "options": ["Trennt Netzwerk- von Hostanteil", "Verdeckt die IP-Adresse", "Ein Passwort für das WLAN", "Die Hardware-Adresse"], "answer": 0 },
        { "question": "Wofür steht 'DNS'?", "options": ["Data Network System", "Domain Name System", "Digital Network Security", "Direct Node Server"], "answer": 1 },
        { "question": "Welches Protokoll wird für 'Ping' verwendet?", "options": ["TCP", "UDP", "ICMP", "HTTP"], "answer": 2 },
        { "question": "Was ist ein 'Default Gateway'?", "options": ["Der Ausgang aus dem lokalen Netz (Router)", "Die IP des eigenen PCs", "Der DNS-Server", "Das WLAN-Passwort"], "answer": 0 },
        { "question": "Welchen Port nutzt HTTP standardmäßig?", "options": ["21", "25", "80", "443"], "answer": 2 },
        { "question": "Was ist der Unterschied zwischen TCP und UDP?", "options": ["TCP ist verbindungsorientiert, UDP verbindungslos", "UDP ist sicherer", "TCP ist schneller", "Gibt keinen"], "answer": 0 },
        { "question": "Wie wird eine IPv6-Adresse dargestellt?", "options": ["Dezimal", "Binär", "Hexadezimal", "Oktal"], "answer": 2 },
        { "question": "Was ist ein 'Layer-3-Switch'?", "options": ["Switch mit Routing-Funktionen", "Ein Switch mit 3 Ports", "Ein besonders kleiner Switch", "Ein Switch für Schicht 7"], "answer": 0 },
        { "question": "Wofür wird DHCP verwendet?", "options": ["Automatische Zuweisung von IP-Konfigurationen", "Namensauflösung", "Verschlüsselung", "Übertragung von Dateien"], "answer": 0 },
        { "question": "Was ist eine MAC-Adresse?", "options": ["Eindeutige Hardware-Adresse der Netzwerkkarte", "Die IP-Adresse eines MacBooks", "Ein Sicherheitszertifikat", "Die Adresse des Routers"], "answer": 0 },
        { "question": "Was ist 'NAT'?", "options": ["Network Address Translation", "Netzwerk-Analyse-Tool", "New Access Technology", "Node Authentication Task"], "answer": 0 },
        { "question": "Welche PDU gehört zu Schicht 4 (Transport)?", "options": ["Bit", "Frame", "Paket", "Segment"], "answer": 3 },
        { "question": "Was bedeutet 'Dual Stack' bei IPv6?", "options": ["Gleichzeitiger Betrieb von IPv4 und IPv6", "Zwei Netzwerkkarten", "Doppelte Geschwindigkeit", "Zwei Router"], "answer": 0 }
      ]
    },
    {
      "title": "WLAN und VLAN",
      "id": "wlan_vlan",
      "description": "Standards (Wifi 6), Sicherheit (WPA3), VLAN Tagging, VPN.",
      "priority": "sehr hoch",
      "questions": [
        { "question": "Welcher WLAN-Standard ist 'Wifi 6'?", "options": ["802.11n", "802.11ac", "802.11ax", "802.11be"], "answer": 2 },
        { "question": "Welche Verschlüsselung ist aktuell der sicherste Standard für WLAN?", "options": ["WEP", "WPA", "WPA2", "WPA3"], "answer": 3 },
        { "question": "Was ist ein 'VLAN'?", "options": ["Virtuelles lokales Netzwerk (logische Trennung)", "Ein besonders schnelles LAN", "WLAN per Kabel", "Ein Netzwerk für Videos"], "answer": 0 },
        { "question": "Was bedeutet 'Tagging' (802.1Q) bei VLANs?", "options": ["Markierung von Frames zur Zuordnung zu einem VLAN", "Namensschilder an Kabeln", "Priorisierung von Sprachdaten", "Sperren von Ports"], "answer": 0 },
        { "question": "Was ist ein 'Trunk Port'?", "options": ["Ein Port, der mehrere VLANs überträgt", "Ein Port für Drucker", "Ein defekter Port", "Ein Port nur für das Management"], "answer": 0 },
        { "question": "Welche Frequenzen nutzt Wifi 6?", "options": ["Nur 2,4 GHz", "Nur 5 GHz", "2,4 GHz und 5 GHz", "60 GHz"], "answer": 2 },
        { "question": "Was ist 'VPN'?", "options": ["Virtual Private Network (sichere Tunnelverbindung)", "Very Private Node", "Verified Port Number", "Visual Path Network"], "answer": 0 },
        { "question": "Was ist ein 'Access Point'?", "options": ["Basisstation für kabellose Netzwerkgeräte", "Ein Switch-Port", "Der Internetanschluss", "Ein Server"], "answer": 0 },
        { "question": "Wofür steht 'SSID'?", "options": ["System Security ID", "Service Set Identifier (WLAN-Name)", "Secure Signal ID", "Super Speed ID"], "answer": 1 },
        { "question": "Was ist 'MIMO' bei WLAN?", "options": ["Multiple Input Multiple Output (mehrere Antennen)", "Mini Modulator", "Musik im Netz", "Mobile Interface"], "answer": 0 },
        { "question": "Was ist 'IPsec'?", "options": ["Protokoll-Suite zur Sicherung von IP-Kommunikation (VPN)", "Eine IP-Adresse", "Ein Internet-Provider", "Ein Switch-Hersteller"], "answer": 0 },
        { "question": "Was ist 'Site-to-Site VPN'?", "options": ["Verbindung zweier Standorte über das Internet", "Verbindung eines Laptops zum Server", "WLAN im Büro", "Internet im Flugzeug"], "answer": 0 },
        { "question": "Was ist ein 'Captive Portal'?", "options": ["Anmeldeseite in öffentlichen WLANs", "Ein verschlossener Serverraum", "Ein Virus im Browser", "Das Router-Menü"], "answer": 0 },
        { "question": "Was bewirkt 'WPS' (Wifi Protected Setup)?", "options": ["Einfache Verbindung per Knopfdruck (Sicherheitsrisiko)", "Verschlüsselung der Festplatte", "Schnelleres Internet", "Automatische Updates"], "answer": 0 },
        { "question": "Was ist 'PoE' (Power over Ethernet)?", "options": ["Stromversorgung von Geräten über das LAN-Kabel", "Internet über das Stromnetz", "Ein schnellerer Port", "Besonders dicke Kabel"], "answer": 0 },
        { "question": "Was ist der Vorteil von 5 GHz gegenüber 2,4 GHz WLAN?", "options": ["Höhere Datenrate, weniger Störungen", "Höhere Reichweite", "Durchdringt Wände besser", "Ist kostenlos"], "answer": 0 },
        { "question": "Was ist 'Beamforming'?", "options": ["Gezielte Ausrichtung des WLAN-Signals zum Client", "Ein spezielles Kabel", "Ein Dateiformat", "Ein Antiviren-Tool"], "answer": 0 },
        { "question": "Was ist 'Dynamic VLAN'?", "options": ["Zuordnung zum VLAN basierend auf der MAC/User", "VLAN, das sich ständig ändert", "Ein VLAN für Videos", "Gibt es nicht"], "answer": 0 },
        { "question": "Welcher Standard regelt VLAN Tagging?", "options": ["IEEE 802.1Q", "IEEE 802.3", "IEEE 802.11", "RFC 1918"], "answer": 0 },
        { "question": "Was ist 'Roaming' im WLAN?", "options": ["Automatischer Wechsel zwischen Access Points", "Surfen im Ausland", "Ein kaputtes Signal", "Die Reichweite erhöhen"], "answer": 0 }
      ]
    },
    {
      "title": "Speicher und Backup",
      "id": "backup",
      "description": "Backup-Arten, Generationenprinzip, 3-2-1 Regel, NAS, RAID.",
      "priority": "sehr hoch",
      "questions": [
        { "question": "Was sichert ein 'Inkrementelles Backup'?", "options": ["Alle Daten", "Nur Daten seit dem letzten Voll-Backup", "Nur Daten seit dem letzten Backup (egal welcher Art)", "Nur gelöschte Dateien"], "answer": 2 },
        { "question": "Was besagt die '3-2-1 Regel' der Datensicherung?", "options": ["3 Kopien, 2 Medien, 1 Off-site", "3 Server, 2 Backups, 1 Admin", "3 Tage, 2 Wochen, 1 Monat", "3 MB, 2 GB, 1 TB"], "answer": 0 },
        { "question": "Welches Backup benötigt bei der Wiederherstellung am meisten Zeit/Medien?", "options": ["Voll-Backup", "Differentielles Backup", "Inkrementelles Backup", "Spiegelung"], "answer": 2 },
        { "question": "Was ist das 'Generationenprinzip'?", "options": ["Großvater-Vater-Sohn (Rotation von Sicherungen)", "Alte Mitarbeiter lehren junge", "Hardware wird alle 3 Jahre ersetzt", "Backup nur für Senioren"], "answer": 0 },
        { "question": "Was ist ein 'NAS'?", "options": ["Network Attached Storage (Speicher im Netz)", "New Access System", "Network Application Server", "Node Archiving System"], "answer": 0 },
        { "question": "Welcher RAID-Level bietet Mirroring (Spiegelung)?", "options": ["RAID 0", "RAID 1", "RAID 5", "RAID 10"], "answer": 1 },
        { "question": "Was ist der Hauptvorteil von RAID 5?", "options": ["Maximale Geschwindigkeit", "Kombination aus Performance und Redundanz (Parität)", "Nur Speicherplatz", "Einfachste Einrichtung"], "answer": 1 },
        { "question": "Was ist ein 'SAN'?", "options": ["Storage Area Network (dediziertes Speichernetzwerk)", "System Area Node", "Secure Access Network", "Server Attached Node"], "answer": 0 },
        { "question": "Was ist 'Cold Standby'?", "options": ["Ersatzhardware, die erst konfiguriert werden muss", "Hardware im Kühlschrank", "Laufendes System als Kopie", "Ein Backup auf Band"], "answer": 0 },
        { "question": "Was ist 'Differentielles Backup'?", "options": ["Alle Änderungen seit dem letzten Vollbackup", "Alle Änderungen seit gestern", "Nur neue Dateien", "Ein Backup von Linux auf Windows"], "answer": 0 },
        { "question": "Was ist 'RAID 0'?", "options": ["Striping (keine Redundanz, nur Speed)", "Spiegelung", "Parität", "Sicherheit pur"], "answer": 0 },
        { "question": "Was bedeutet 'Hot-Swap'?", "options": ["Tausch von Hardware (z.B. HDD) im laufenden Betrieb", "Tausch von Kaffee", "Langsamer Tausch", "Tausch nach dem Ausschalten"], "answer": 0 },
        { "question": "Wofür steht 'WORM' bei Speichermedien?", "options": ["Write Once Read Many (Revisionssicherheit)", "Ein Computervirus", "Write Often Read More", "Wireless Optical Reading Module"], "answer": 0 },
        { "question": "Was ist eine 'Snapshot' Sicherung?", "options": ["Augenblickliche Abbildung des Datenzustands (VMs)", "Ein Foto vom Server", "Ein kurzes Backup", "Ein Backup auf USB-Stick"], "answer": 0 },
        { "question": "Welche Backup-Art ist am schnellsten durchgeführt?", "options": ["Voll-Backup", "Inkrementelles Backup", "Differentielles Backup", "RAID 1"], "answer": 1 },
        { "question": "Was ist 'Disaster Recovery'?", "options": ["Wiederherstellung nach einem Totalausfall", "Vermeidung von Fehlern", "Löschen von Daten", "Ein Betriebssystem-Update"], "answer": 0 },
        { "question": "Wieviele Festplatten dürfen bei RAID 5 maximal ausfallen?", "options": ["Keine", "Eine", "Zwei", "Die Hälfte"], "answer": 1 },
        { "question": "Was ist der Unterschied zwischen Backup und Archivierung?", "options": ["Backup = Wiederherstellung, Archiv = Langzeitaufbewahrung", "Keiner", "Backup ist immer teurer", "Archivierung ist nur für Papier"], "answer": 0 },
        { "question": "Was ist 'Cloud Backup'?", "options": ["Sicherung auf Servern im Internet", "Sicherung wenn es regnet", "Sicherung auf CD", "Sicherung im lokalen Netz"], "answer": 0 },
        { "question": "Was ist 'Parität' beim RAID?", "options": ["Prüfsumme zur Wiederherstellung von Daten", "Die Anzahl der Festplatten", "Die Drehzahl der Platten", "Ein Verbindungskabel"], "answer": 0 }
      ]
    },
    {
      "title": "IT Berechnungen",
      "id": "berechnungen",
      "description": "Übertragungsdauer, Speicherbedarf, Zahlensysteme, Einheiten (Mbit vs MB).",
      "priority": "sehr hoch",
      "questions": [
        { "question": "Wie rechnet man von Megabyte (MB) in Megabit (Mbit) um?", "options": ["Faktor 2", "Faktor 4", "Faktor 8", "Faktor 10"], "answer": 2 },
        { "question": "Was ist der Dezimalwert der Binärzahl 1010?", "options": ["5", "8", "10", "12"], "answer": 2 },
        { "question": "Wie viele Bytes sind ein Kibibyte (KiB)?", "options": ["1000", "1024", "1048", "2048"], "answer": 1 },
        { "question": "Berechnung der Übertragungsdauer: 800 MB bei 100 Mbit/s?", "options": ["8 Sekunden", "64 Sekunden", "80 Sekunden", "800 Sekunden"], "answer": 1 },
        { "question": "Wie viele Zustände können mit 8 Bit dargestellt werden?", "options": ["8", "16", "128", "256"], "answer": 3 },
        { "question": "Was ist der Hex-Wert für die Dezimalzahl 15?", "options": ["A", "E", "F", "10"], "answer": 2 },
        { "question": "Speicherbedarf eines Bildes: 100x100 Pixel, 24 Bit Farbtiefe (in Byte)?", "options": ["10.000", "30.000", "240.000", "300.000"], "answer": 1 },
        { "question": "Was bedeutet das Präfix 'Giga'?", "options": ["10^3 (Tausend)", "10^6 (Million)", "10^9 (Milliarde)", "10^12 (Billion)"], "answer": 2 },
        { "question": "Umrechnung: 1 TB sind wie viele GB (dezimal/SI)?", "options": ["100", "1000", "1024", "2000"], "answer": 1 },
        { "question": "Wie viel Bit sind ein IPv4 Header (Minimum)?", "options": ["20 Byte = 160 Bit", "32 Bit", "128 Bit", "1 Byte"], "answer": 0 },
        { "question": "Was ist 17 hexadezimal in dezimal?", "options": ["17", "23", "31", "117"], "answer": 1 },
        { "question": "Wie rechnet man von km/h in m/s (für IT-Kabel irrelevant, aber oft in Prüfungen)?", "options": ["* 3,6", "/ 3,6", "+ 3,6", "- 3,6"], "answer": 1 },
        { "question": "Speicherbedarf Audio: 1 Min, 44,1 kHz, 16 Bit, Mono (ca.)?", "options": ["1 MB", "5 MB", "10 MB", "100 MB"], "answer": 1 },
        { "question": "Was ist die Basis des Hexadezimalsystems?", "options": ["2", "8", "10", "16"], "answer": 3 },
        { "question": "Wie viele Adressen hat ein /28 Subnetz?", "options": ["14 nutzbare (16 gesamt)", "30 nutzbare (32 gesamt)", "62 nutzbare (64 gesamt)", "254 nutzbare"], "answer": 0 },
        { "question": "Was ist die binäre Darstellung von 255?", "options": ["00000000", "10101010", "11111111", "10000000"], "answer": 2 },
        { "question": "Was ist ein 'Nibble'?", "options": ["1 Bit", "4 Bit", "8 Bit", "16 Bit"], "answer": 1 },
        { "question": "Formel für Übertragungszeit?", "options": ["t = s / v (Zeit = Weg/Geschwindigkeit)", "t = Datenmenge / Datenrate", "t = Preis / Leistung", "t = m * c^2"], "answer": 1 },
        { "question": "Was ist der Unterschied zwischen MB und MiB?", "options": ["MB = 1000^2, MiB = 1024^2", "Keiner", "MiB ist für Apple", "MB ist schneller"], "answer": 0 },
        { "question": "Wie viele Byte hat ein Standard-Ethernet-Frame (MTU)?", "options": ["64", "512", "1500", "9000"], "answer": 2 }
      ]
    }
  ]
};
