quizData.chapters.push({
  "title": "Lernfeld 1: Unternehmen und Prozesse",
  "priority": 1,
  "subsections": [
    {
      "title": "Markt und Unternehmensziele",
      "id": "markt",
      "description": "Marktformen, Ökonomisches Prinzip, Zielgruppen, SMART-Ziele.",
      "priority": "hoch",
      "questions": [
        { "question": "Was beschreibt das Maximalprinzip?", "options": ["Gegebene Mittel für maximalen Erfolg", "Festes Ziel mit minimalen Mitteln", "Viel Output bei viel Input", "Gleiche Mittel für gleiches Ziel"], "answer": 0 },
        { "question": "Welche Marktform kennzeichnet viele Anbieter und Nachfrager?", "options": ["Monopol", "Oligopol", "Polypol", "Kartell"], "answer": 2 },
        { "question": "Was ist eine SMART-konforme Zielformulierung?", "options": ["Wir wollen mehr Umsatz", "Steigerung des Umsatzes um 10% bis 31.12.", "Wir wollen besser werden als die Konkurrenz", "Kundenzufriedenheit erhöhen"], "answer": 1 },
        { "question": "Was gehört zu ökonomischen Zielen?", "options": ["Gewinnmaximierung", "CO2-Neutralität", "Mitarbeiterzufriedenheit", "Lärmschutz"], "answer": 0 },
        { "question": "Was ist der Unterschied zwischen Käufer- und Verkäufermarkt?", "options": ["Keiner", "Angebot > Nachfrage bei Käufermarkt", "Angebot < Nachfrage bei Käufermarkt", "Nur der Preis zählt"], "answer": 1 },
        { "question": "Welches Kriterium ist psychografisch bei der Zielgruppendefinition?", "options": ["Alter", "Werte/Lifestyle", "Wohnort", "Beruf"], "answer": 1 },
        { "question": "Was bedeutet Zielharmonie?", "options": ["Ziele schließen sich aus", "Ziele unterstützen sich gegenseitig", "Ziele sind unabhängig voneinander", "Ziele sind unerreichbar"], "answer": 1 },
        { "question": "Welche Marktform hat nur einen Anbieter?", "options": ["Monopol", "Oligopol", "Polypol", "Duopol"], "answer": 0 },
        { "question": "Was ist der Tertiärsektor?", "options": ["Urproduktion (Landwirtschaft)", "Industrie/Handwerk", "Dienstleistungen", "Öffentlicher Dienst"], "answer": 2 },
        { "question": "Was besagt das Minimalprinzip?", "options": ["Festes Ziel mit minimalem Aufwand", "Maximaler Erfolg mit festem Einsatz", "Viel Aufwand, viel Ertrag", "Wenig Aufwand, wenig Ertrag"], "answer": 0 },
        { "question": "Was ist ein 'Nischenmarkt'?", "options": ["Ein Markt mit sehr vielen Wettbewerbern", "Ein Marktsegment mit speziellen Bedürfnissen", "Ein Markt ohne Kunden", "Ein Markt für billige Produkte"], "answer": 1 },
        { "question": "Was beschreibt die 'Preiselastizität'?", "options": ["Wie stark die Nachfrage auf Preisänderungen reagiert", "Wie schnell sich Preise im Supermarkt ändern", "Die Haltbarkeit von Preisschildern", "Die Inflation"], "answer": 0 },
        { "question": "Welche Zielbeziehung liegt vor, wenn das Erreichen von Ziel A das Ziel B verhindert?", "options": ["Zielharmonie", "Zielkonflikt", "Zielindifferenz", "Zielkomplementarität"], "answer": 1 },
        { "question": "Was ist ein 'Oligopol'?", "options": ["Ein Anbieter, viele Nachfrager", "Viele Anbieter, ein Nachfrager", "Wenige Anbieter, viele Nachfrager", "Ein Anbieter, ein Nachfrager"], "answer": 2 },
        { "question": "Was gehört zu den ökologischen Zielen eines Unternehmens?", "options": ["Umsatzsteigerung", "Ressourceneffizienz", "Marktanteilsvergrößerung", "Kostenreduktion"], "answer": 1 },
        { "question": "Was bedeutet 'S' in der SMART-Formel?", "options": ["Sinnvoll", "Spezifisch", "Schnell", "Sicher"], "answer": 1 },
        { "question": "Was ist ein Verkäufermarkt?", "options": ["Nachfrage > Angebot", "Angebot > Nachfrage", "Nachfrage = Angebot", "Es gibt keine Käufer"], "answer": 0 },
        { "question": "Welches Ziel ist sozial?", "options": ["Gewinn", "Arbeitsplatzsicherung", "Abgasreduzierung", "Eigenkapitalrendite"], "answer": 1 },
        { "question": "Was bedeutet Zielindifferenz?", "options": ["Ziele fördern sich", "Ziele behindern sich", "Ziele beeinflussen sich nicht", "Ziele sind identisch"], "answer": 2 },
        { "question": "Welche Zielgruppe wird nach geografischen Merkmalen definiert?", "options": ["Werteorientierte Menschen", "Kaufkraftstarke Haushalte", "Einwohner von Berlin", "Jugendliche zwischen 14 und 18"], "answer": 2 }
      ]
    },
    {
      "title": "Organisationsstrukturen",
      "id": "orga",
      "description": "Einlinien-, Mehrlinien-, Matrixorganisation, Prokura.",
      "priority": "mittel",
      "questions": [
        { "question": "Was ist ein Vorteil des Einliniensystems?", "options": ["Klare Dienstwege", "Kurze Entscheidungswege", "Keine Hierarchie", "Hohe Spezialisierung"], "answer": 0 },
        { "question": "Was ist ein Nachteil des Mehrliniensystems?", "options": ["Lange Wege", "Kompetenzkonflikte", "Zu wenig Fachwissen", "Starre Strukturen"], "answer": 1 },
        { "question": "Was macht eine Stabsstelle?", "options": ["Beratung der Geschäftsführung", "Operative Produktion", "Direkter Verkauf", "Personalverwaltung"], "answer": 0 },
        { "question": "Was darf ein Prokurist NICHT?", "options": ["Verträge schließen", "Das Unternehmen als Ganzes verkaufen", "Mitarbeiter einstellen", "Darlehen aufnehmen"], "answer": 1 },
        { "question": "Welche Vollmacht erlaubt alle gewöhnlichen Geschäfte eines Betriebs?", "options": ["Prokura", "Handlungsvollmacht", "Einzelvollmacht", "Generalvollmacht"], "answer": 1 },
        { "question": "Was zeichnet die Matrixorganisation aus?", "options": ["Einliniensystem", "Zwei-Wege-System (z.B. Produkt und Funktion)", "Keine Hierarchie", "Nur Stabsstellen"], "answer": 1 },
        { "question": "Was ist ein Nachteil der Matrixorganisation?", "options": ["Hoher Abstimmungsbedarf", "Zu schnelle Entscheidungen", "Klare Unterstellung", "Einfache Struktur"], "answer": 0 },
        { "question": "Was bedeutet 'ppa.' vor einer Unterschrift?", "options": ["per procura (Prokurist)", "pro parte (Teilbevollmächtigung)", "persönlich passend", "per Post"], "answer": 0 },
        { "question": "Was kennzeichnet die Divisionale Struktur?", "options": ["Gliederung nach Sparten/Produkten", "Rein funktionale Gliederung", "Flache Hierarchien ohne Abteilungen", "Nur Matrixform"], "answer": 0 },
        { "question": "Was ist das 'Vier-Augen-Prinzip'?", "options": ["Kontrolle durch zwei Personen", "Brille tragen", "Zwei Chefs haben", "Matrixorganisation"], "answer": 0 },
        { "question": "Welches System hat kurze Wege, aber birgt die Gefahr widersprüchlicher Anweisungen?", "options": ["Einliniensystem", "Mehrliniensystem", "Stabliniensystem", "Spartenorganisation"], "answer": 1 },
        { "question": "Warum wird die Stabstelle oft als 'graue Eminenz' bezeichnet?", "options": ["Sie hat viel Wissen, aber keine Weisungsbefugnis", "Sie trägt nur graue Anzüge", "Sie sitzt im Keller", "Sie ist der wahre Chef"], "answer": 0 },
        { "question": "Was ist eine 'funktionsorientierte' Organisation?", "options": ["Gliederung nach Aufgaben (Einkauf, Verkauf etc.)", "Gliederung nach Regionen", "Gliederung nach Kunden", "Gliederung nach Projekten"], "answer": 0 },
        { "question": "Welche Vollmacht erlischt NICHT automatisch mit dem Tod des Inhabers?", "options": ["Prokura", "Handlungsvollmacht", "Spezialvollmacht", "Einzelvollmacht"], "answer": 0 },
        { "question": "Was ist ein Vorteil der Matrixorganisation?", "options": ["Spezialisierung der Führungskräfte", "Schnelle Entscheidungen", "Klare Zuständigkeit", "Geringer Konflikt"], "answer": 0 },
        { "question": "Wer erteilt die Prokura?", "options": ["Der Firmeninhaber/GF persönlich", "Das Amtsgericht", "Der Betriebsrat", "Jeder Abteilungsleiter"], "answer": 0 },
        { "question": "Was ist eine Generalvollmacht?", "options": ["Vollmacht für alle Arten von Geschäften", "Vollmacht nur für die Post", "Vollmacht für einen Tag", "Vollmacht für einen Einkauf"], "answer": 0 },
        { "question": "Was ist eine Stabliniensorganisation?", "options": ["Einliniensystem mit beratenden Stellen", "Mehrliniensystem", "Flache Struktur", "Spartenmodell"], "answer": 0 },
        { "question": "Was ist ein Organigramm?", "options": ["Grafische Darstellung der Aufbauorganisation", "Eine Liste aller Mitarbeiter", "Der Urlaubsplan", "Ein technisches Diagramm"], "answer": 0 },
        { "question": "Welche Organisation eignet sich am besten für Großunternehmen mit vielen Produkten?", "options": ["Spartenorganisation", "Einliniensystem", "Stabliniensystem", "Einzelunternehmen"], "answer": 0 }
      ]
    },
    {
      "title": "Vertragsrecht und Störungen",
      "id": "recht",
      "description": "Kauf-, Werk-, Dienstverträge, SLAs, Mängel, Verzug.",
      "priority": "sehr hoch",
      "questions": [
        { "question": "Welcher Vertrag schuldet einen konkreten Erfolg?", "options": ["Dienstvertrag", "Werkvertrag", "Leasingvertrag", "Arbeitsvertrag"], "answer": 1 },
        { "question": "Wie hoch ist die regelmäßige Verjährungsfrist laut BGB?", "options": ["2 Jahre", "3 Jahre", "5 Jahre", "10 Jahre"], "answer": 1 },
        { "question": "Was ist ein Sachmangel?", "options": ["Defekt bei Lieferung", "Verkäufer ist nicht Eigentümer", "Preis ist zu hoch", "Lieferung erfolgt zu spät"], "answer": 0 },
        { "question": "Welches Recht hat der Käufer vorrangig bei einem Mangel?", "options": ["Rücktritt", "Nacherfüllung", "Minderung", "Schadenersatz"], "answer": 1 },
        { "question": "Was ist ein Dienstvertrag im IT-Bereich?", "options": ["Software-Entwicklung (Erfolg)", "Stundenweise IT-Beratung", "Kauf eines Laptops", "Miete eines Servers"], "answer": 1 },
        { "question": "Wann liegt ein Rechtsmangel vor?", "options": ["Das Gerät ist kaputt", "Dritte können Rechte geltend machen (z.B. kein Eigentum)", "Die Bedienungsanleitung fehlt", "Die Farbe ist falsch"], "answer": 1 },
        { "question": "Wann beginnt die regelmäßige Verjährungsfrist?", "options": ["Am Tag des Kaufs", "Am Ende des Jahres, in dem der Anspruch entstand", "Nach der ersten Mahnung", "Nach 6 Monaten"], "answer": 1 },
        { "question": "Welche Form ist für den Abschluss eines Kaufvertrags über bewegliche Sachen (z.B. PC) nötig?", "options": ["Schriftform", "Notarielle Beurkundung", "Formfrei (mündlich/konkludent)", "Textform (E-Mail)"], "answer": 2 },
        { "question": "Was ist eine Falschlieferung (Aliud)?", "options": ["Zu wenig Ware", "Andere Ware als bestellt", "Defekte Ware", "Beschädigte Verpackung"], "answer": 1 },
        { "question": "Was ist die Voraussetzung für Lieferungsverzug?", "options": ["Sofortiger Rücktritt des Käufers", "Fälligkeit und Mahnung (sofern nicht entbehrlich)", "Nichtannahme durch den Käufer", "Schadenersatzforderung"], "answer": 1 },
        { "question": "Was unterscheidet Leasing von Miete?", "options": ["Leasing beinhaltet oft Wartung/Kaufoption", "Leasing ist immer kostenlos", "Miete ist nur für Immobilien", "Es gibt keinen rechtlichen Unterschied"], "answer": 0 },
        { "question": "Was ist ein SLA (Service Level Agreement)?", "options": ["Vereinbarung über Dienstgüte (z.B. Verfügbarkeit)", "Ein Software-Lizenzvertrag", "Ein Sicherheitsgesetz", "Ein Speicherprotokoll"], "answer": 0 },
        { "question": "Was bedeutet 'Gewährleistung'?", "options": ["Gesetzliche Haftung für Mängel bei Übergabe", "Freiwilliges Versprechen des Herstellers", "Versicherung gegen Diebstahl", "Rückgaberecht bei Nichtgefallen"], "answer": 0 },
        { "question": "Wie lange ist die Gewährleistungsfrist beim Kauf von Neuware für Verbraucher?", "options": ["6 Monate", "12 Monate", "24 Monate", "5 Jahre"], "answer": 2 },
        { "question": "Was ist ein Werkvertrag?", "options": ["Reparatur eines Servers", "Beratungsgespräch", "Miete eines Büros", "Abo einer Zeitschrift"], "answer": 0 },
        { "question": "Wann ist eine Mahnung bei Lieferverzug entbehrlich?", "options": ["Bei Fixgeschäften (Termin genau bestimmt)", "Immer", "Nie", "Wenn der Käufer privat ist"], "answer": 0 },
        { "question": "Was ist 'Schlechtleistung'?", "options": ["Lieferung mangelhafter Ware", "Zu späte Lieferung", "Gar keine Lieferung", "Zahlung zu spät"], "answer": 0 },
        { "question": "Was bedeutet 'Eigentumsvorbehalt'?", "options": ["Ware bleibt bis zur vollständigen Zahlung Eigentum des Verkäufers", "Ware darf nicht benutzt werden", "Ware ist reserviert", "Ware ist geliehen"], "answer": 0 },
        { "question": "Was ist der Unterschied zwischen Garantie und Gewährleistung?", "options": ["Garantie ist freiwillig, Gewährleistung gesetzlich", "Garantie ist immer 2 Jahre", "Es ist dasselbe", "Gewährleistung gilt nur für Firmen"], "answer": 0 },
        { "question": "Welches Dokument definiert Reaktionszeiten im Support?", "options": ["SLA", "AGB", "BGB", "ISO 9001"], "answer": 0 }
      ]
    },
    {
      "title": "Change Management",
      "id": "change",
      "description": "Phasen, Rollen, Maßnahmen, Widerstände.",
      "priority": "hoch",
      "questions": [
        { "question": "Welche Phase folgt in der Akzeptanzkurve direkt auf den 'Schock'?", "options": ["Integration", "Verleugnung", "Einsicht", "Ausprobieren"], "answer": 1 },
        { "question": "Wer treibt Veränderungen aktiv und überzeugt an?", "options": ["Bremser", "Promotoren", "Skeptiker", "Widerständler"], "answer": 1 },
        { "question": "Was bedeutet 'Partizipation' im Change Management?", "options": ["Einbeziehung der Betroffenen in den Prozess", "Strenge Kontrolle der Mitarbeiter", "Auslagerung von Aufgaben", "Ignorieren von Kritik"], "answer": 0 },
        { "question": "Was ist eine häufige Ursache für Widerstand gegen Veränderung?", "options": ["Angst vor Statusverlust oder Überforderung", "Zu viel Freizeit", "Höheres Gehalt", "Bessere Hardware"], "answer": 0 },
        { "question": "Welche Rolle äußert sachliche Kritik, ist aber grundsätzlich offen?", "options": ["Skeptiker", "Bremser", "Widerständler", "Promotor"], "answer": 0 },
        { "question": "Was ist das wichtigste Instrument, um Ängste abzubauen?", "options": ["Kommunikation und Information", "Höhere Strafen", "Mehr Überstunden", "Neue Software"], "answer": 0 },
        { "question": "Welche Rolle sabotiert Veränderungen aktiv (auch verdeckt)?", "options": ["Skeptiker", "Widerständler", "Bremser", "Multiplikator"], "answer": 1 },
        { "question": "Was beschreibt die Phase der 'Einsicht'?", "options": ["Erkennen, dass Veränderung notwendig ist", "Völlige Ablehnung", "Perfekte Beherrschung des Neuen", "Erster Schock"], "answer": 0 },
        { "question": "Was ist 'Blended Learning'?", "options": ["Rein digitales Lernen", "Kombination aus Präsenzunterricht und E-Learning", "Lernen während der Arbeit", "Lernen ohne Lehrer"], "answer": 1 },
        { "question": "Was ist die Aufgabe von 'Multiplikatoren'?", "options": ["Widerstand organisieren", "Wissen und positive Einstellung weitertragen", "Fehler in der Software finden", "Die Kosten erhöhen"], "answer": 1 },
        { "question": "Was beschreibt die Akzeptanzkurve?", "options": ["Den technischen Verlauf eines Rollouts", "Den psychologischen Prozess der Anpassung", "Die Umsatzentwicklung nach einem Change", "Die CPU-Last während eines Updates"], "answer": 1 },
        { "question": "Was ist ein 'Bremser'?", "options": ["Jemand, der passiv Widerstand leistet", "Jemand, der aktiv nach Fehlern sucht", "Der Projektleiter", "Der externe Berater"], "answer": 0 },
        { "question": "In welcher Phase ist die Leistungsfähigkeit am geringsten?", "options": ["Schock/Verleugnung", "Einsicht/Ausprobieren", "Integration", "Vorbereitung"], "answer": 1 },
        { "question": "Was bedeutet 'Refreezing' im Modell von Kurt Lewin?", "options": ["Stabilisierung der neuen Zustände", "Einfrieren des Projekts (Abbruch)", "Kündigung der Mitarbeiter", "Serverneustart"], "answer": 0 },
        { "question": "Was ist 'Unfreezing'?", "options": ["Vorbereitung auf den Wandel, Aufbrechen alter Strukturen", "Auftauen von Tiefkühlkost", "Löschen von Daten", "Beginn der Testphase"], "answer": 0 },
        { "question": "Warum ist Partizipation zeitaufwendig, aber wertvoll?", "options": ["Höhere Akzeptanz und bessere Lösungen", "Man kann Verantwortung abschieben", "Mitarbeiter arbeiten dann umsonst", "Es kostet weniger Geld"], "answer": 0 },
        { "question": "Was ist ein 'Wandlungspromotor'?", "options": ["Jemand mit Macht, der den Wandel stützt", "Ein Werbeplakat", "Ein Softwaretool", "Ein unzufriedener Kunde"], "answer": 0 },
        { "question": "Was ist die 'Lernstatt'-Methode?", "options": ["Kleingruppen diskutieren Probleme im Arbeitsbereich", "Ein großer Hörsaal", "Online-Kurs", "Einzelcoaching"], "answer": 0 },
        { "question": "Was ist ein 'Kick-off Meeting'?", "options": ["Startveranstaltung eines Projekts zur Motivation/Info", "Abschlussfeier", "Krisensitzung", "Kaffeepause"], "answer": 0 },
        { "question": "Welches Gefühl dominiert oft die erste Phase (Schock)?", "options": ["Euphorie", "Überrumpelung/Angst", "Langeweile", "Wissensdurst"], "answer": 1 }
      ]
    }
  ]
});
