quizData.chapters.push({
  "title": "Lernfeld 5: Software und Entwicklung",
  "priority": 5,
  "subsections": [
    {
      "title": "Projektmanagement",
      "id": "pm",
      "description": "Phasenmodelle (Wasserfall, Scrum), Netzplan, Lasten- und Pflichtenheft.",
      "priority": "sehr hoch",
      "questions": [
        { "question": "Was ist der Hauptunterschied zwischen Wasserfallmodell und Scrum?", "options": ["Wasserfall ist agil, Scrum ist linear", "Wasserfall ist linear/sequenziell, Scrum ist iterativ", "Es gibt keinen Unterschied", "Scrum braucht keine Dokumentation"], "answer": 1 },
        { "question": "Was beschreibt der 'Kritische Pfad' im Netzplan?", "options": ["Der kürzeste Weg durch das Projekt", "Der Weg ohne Zeitpuffer (Gesamtpuffer = 0)", "Ein Weg mit besonders vielen Risiken", "Die Verbindung aller Meilensteine"], "answer": 1 },
        { "question": "Wer erstellt in der Regel das Lastenheft?", "options": ["Der Auftragnehmer", "Der Auftraggeber", "Der Projektleiter", "Das Entwicklungsteam"], "answer": 1 },
        { "question": "Was ist das Ziel des Pflichtenhefts?", "options": ["Beschreibung, WIE der Auftragnehmer die Anforderungen löst", "Auflistung aller Wünsche des Kunden", "Ein Marketing-Dokument", "Eine Liste aller Mitarbeiter"], "answer": 0 },
        { "question": "Was bedeutet 'SMART' bei Projektzielen?", "options": ["Spezifisch, Messbar, Akzeptiert, Realistisch, Terminiert", "Schnell, Modern, Attraktiv, Robust, Teuer", "Sicher, Mobil, Aktiv, Relevant, Toll", "Systematisch, Methodisch, Analytisch, Rational, Technisch"], "answer": 0 },
        { "question": "Was ist ein 'Meilenstein'?", "options": ["Ein schwerer Stein im Garten", "Ein Ereignis von besonderer Bedeutung (Checkpunkt)", "Eine Zeiteinheit von einem Monat", "Ein Mitarbeiter des Monats"], "answer": 1 },
        { "question": "Was zeigt ein Gantt-Diagramm?", "options": ["Die logische Verknüpfung von Aufgaben", "Die zeitliche Abfolge von Aufgaben auf einer Zeitachse", "Die Hierarchie im Unternehmen", "Den Programmcode"], "answer": 1 },
        { "question": "Was ist der 'Gesamtpuffer' im Netzplan?", "options": ["Zeit, um die sich ein Vorgang verschieben lässt, ohne das Projektende zu gefährden", "Zeit bis zum nächsten Urlaub", "Puffer für die Kaffeepause", "Die maximale Dauer eines Vorgangs"], "answer": 0 },
        { "question": "Was ist ein 'Backlog' in Scrum?", "options": ["Eine Liste aller noch zu erledigenden Anforderungen", "Ein Fehler im Programm", "Das Archiv des Projekts", "Die Mittagspause"], "answer": 0 },
        { "question": "Wer ist im Scrum für die Priorisierung des Product Backlogs verantwortlich?", "options": ["Scrum Master", "Product Owner", "Development Team", "Stakeholder"], "answer": 1 },
        { "question": "Wie lange dauert ein 'Sprint' in Scrum üblicherweise?", "options": ["1 Tag", "1 bis 4 Wochen", "6 Monate", "1 Jahr"], "answer": 1 },
        { "question": "Was ist die Aufgabe des Scrum Masters?", "options": ["Programmieren der Software", "Beseitigung von Hindernissen und Prozessbegleitung", "Vorgabe der Termine", "Verkauf des Produkts"], "answer": 1 },
        { "question": "Was ist ein 'Daily Scrum'?", "options": ["Ein tägliches 15-minütiges Meeting zur Abstimmung", "Ein wöchentlicher Bericht", "Das Abendessen des Teams", "Ein Testlauf"], "answer": 0 },
        { "question": "Was passiert im 'Sprint Review'?", "options": ["Präsentation der fertigen Inkremente vor Stakeholdern", "Fehlersuche im Code", "Planung des nächsten Sprints", "Kritik am Scrum Master"], "answer": 0 },
        { "question": "Was ist der 'Freie Puffer' im Netzplan?", "options": ["Zeit, um die ein Vorgang verschoben werden kann, ohne den FRÜHESTEN Start des Nachfolgers zu beeinflussen", "Puffer für das gesamte Projekt", "Zeit für zusätzliche Features", "Ein Puffer, der nichts kostet"], "answer": 0 },
        { "question": "Was bedeutet 'iterativ'?", "options": ["Sich wiederholend (in Schleifen)", "Einmalig", "Gleichzeitig", "Zufällig"], "answer": 0 },
        { "question": "Was ist ein 'Kick-off-Meeting'?", "options": ["Das Abschlusstreffen", "Das Treffen zum Projektstart", "Eine Fußballrunde", "Ein Treffen zur Kündigung"], "answer": 1 },
        { "question": "Was beschreibt die 'Spezifität' in SMART?", "options": ["Ziele müssen konkret und eindeutig formuliert sein", "Ziele müssen besonders teuer sein", "Ziele müssen geheim sein", "Ziele müssen technisch sein"], "answer": 0 },
        { "question": "Was ist das 'Magische Dreieck' des Projektmanagements?", "options": ["Zeit, Kosten, Qualität/Leistung", "Kunde, Chef, Mitarbeiter", "Hardware, Software, Netz", "Input, Output, Durchlauf"], "answer": 0 },
        { "question": "Welches Dokument dient als Grundlage für die Ausschreibung?", "options": ["Lastenheft", "Pflichtenheft", "Arbeitsvertrag", "Rechnung"], "answer": 0 }
      ]
    },
    {
      "title": "Standardsoftware und Trends",
      "id": "trends",
      "description": "ERP, CRM, KI und Barrierefreiheit.",
      "priority": "mittel",
      "questions": [
        { "question": "Wofür steht ERP?", "options": ["Enterprise Resource Planning", "Easy Road Planning", "Electronic Resource Parts", "Extra Remote Processing"], "answer": 0 },
        { "question": "Was ist das Hauptziel eines CRM-Systems?", "options": ["Verwaltung von Kundenbeziehungen", "Steuerung von Maschinen", "Erstellung von Webseiten", "Berechnung der Lohnsteuer"], "answer": 0 },
        { "question": "Was ist SCM?", "options": ["Supply Chain Management (Lieferkettensteuerung)", "Secure Code Management", "System Control Module", "Simple Cloud Memory"], "answer": 0 },
        { "question": "Was versteht man unter 'Barrierefreiheit' bei Software?", "options": ["Nutzbarkeit für Menschen mit Behinderungen", "Kostenlose Software", "Software ohne Kopierschutz", "Software, die überall läuft"], "answer": 0 },
        { "question": "Welche Technologie steckt hinter modernen Sprachmodellen (KI)?", "options": ["Neuronale Netze / Deep Learning", "Einfache Wenn-Dann-Regeln", "Mechanische Relais", "Nur Datenbankabfragen"], "answer": 0 },
        { "question": "Was ist 'Big Data'?", "options": ["Sehr große, komplexe und schnelllebige Datenmengen", "Eine große externe Festplatte", "Ein altes Datenformat", "Daten, die nur auf Großrechnern liegen"], "answer": 0 },
        { "question": "Was bedeutet 'Software as a Service' (SaaS)?", "options": ["Software wird als Dienstleistung über das Internet gemietet", "Software wird einmalig gekauft und installiert", "Der Programmierer kommt ins Haus", "Software ist immer Open Source"], "answer": 0 },
        { "question": "Welcher Trend beschreibt das Internet der Dinge (IoT)?", "options": ["Vernetzung von physischen Objekten mit dem Internet", "Surfen im Web", "Online-Shopping", "Erstellen von Homepages"], "answer": 0 },
        { "question": "Was ist eine 'KI-Halluzination'?", "options": ["Ein Fehler, bei dem die KI plausibel klingende, aber falsche Fakten erfindet", "Wenn die KI abstürzt", "Ein besonders schnelles Rechenergebnis", "Die Benutzeroberfläche"], "answer": 0 },
        { "question": "Was ist der Vorteil eines ERP-Systems?", "options": ["Zentrale Datenhaltung und integrierte Prozesse", "Es ist immer kostenlos", "Man braucht keine IT-Abteilung mehr", "Es ersetzt alle Mitarbeiter"], "answer": 0 },
        { "question": "Was ist 'Cloud Computing'?", "options": ["Bereitstellung von IT-Infrastruktur über das Internet", "Rechnen bei schlechtem Wetter", "Ein spezielles Betriebssystem", "Lokale Datenspeicherung"], "answer": 0 },
        { "question": "Was bedeutet 'Low-Code'?", "options": ["Softwareentwicklung mit wenig manuellem Programmieren (visuell)", "Schlechter Programmierstil", "Kostenlose Software", "Software für alte Computer"], "answer": 0 },
        { "question": "Wofür werden 'Chatbots' primär eingesetzt?", "options": ["Automatisierte Kundenkommunikation", "Virenscan", "Grafikerstellung", "Hardware-Reparatur"], "answer": 0 },
        { "question": "Was ist 'Edge Computing'?", "options": ["Datenverarbeitung nah am Entstehungsort (nahe am Endgerät)", "Rechnen in der Cloud", "Surfen am Rande des Internets", "Besonders scharfe Grafiken"], "answer": 0 },
        { "question": "Was ist 'Predictive Maintenance'?", "options": ["Vorausschauende Wartung basierend auf Daten", "Wartung erst wenn es kaputt ist", "Wartung nach festem Zeitplan", "Wartung durch den Benutzer"], "answer": 0 },
        { "question": "Was ist ein 'Digitaler Zwilling'?", "options": ["Ein digitales Abbild eines physischen Objekts oder Prozesses", "Eine Kopie einer CD", "Ein zweiter Monitor", "Zwei identische Server"], "answer": 0 },
        { "question": "Was versteht man unter 'Blockchain'?", "options": ["Dezentrale, fälschungssichere Datenbankstruktur", "Ein Spiel mit Blöcken", "Eine Kette von Computern", "Ein spezieller USB-Stick"], "answer": 0 },
        { "question": "Was ist 'Responsive Design'?", "options": ["Webseiten, die sich an die Bildschirmgröße anpassen", "Ein Design, das schnell antwortet", "Ein Design nur für Handys", "Ein Design mit vielen Farben"], "answer": 0 },
        { "question": "Was bedeutet 'Green IT'?", "options": ["Umweltfreundliche und ressourcensparende IT", "Grüne Computergehäuse", "IT für die Landwirtschaft", "IT ohne Strom"], "answer": 0 },
        { "question": "Was ist 'Business Intelligence' (BI)?", "options": ["Analyse von Unternehmensdaten zur Entscheidungsfindung", "Spionage beim Wettbewerber", "Ein schlaues ERP-System", "KI für Manager"], "answer": 0 }
      ]
    },
    {
      "title": "UML und Modellierung",
      "id": "uml",
      "description": "Aktivitäts-, Klassen-, Use-Case-Diagramme, ER-Modell, EPK.",
      "priority": "sehr hoch",
      "questions": [
        { "question": "Was stellt ein UML-Aktivitätsdiagramm primär dar?", "options": ["Abläufe und Kontrollfluss", "Struktur von Klassen", "Beziehungen zwischen Datenbanken", "Benutzerrollen"], "answer": 0 },
        { "question": "Wofür steht UML?", "options": ["Unified Modeling Language", "Universal Markup Language", "Unit Method Logic", "Unique Model Layout"], "answer": 0 },
        { "question": "Was zeigt ein Klassendiagramm?", "options": ["Statische Struktur (Attribute, Methoden, Beziehungen)", "Zeitlichen Ablauf", "Physische Server", "Farben der Webseite"], "answer": 0 },
        { "question": "Was symbolisiert eine Raute im Aktivitätsdiagramm?", "options": ["Eine Entscheidung (Verzweigung/Zusammenführung)", "Startpunkt", "Endpunkt", "Eine Aktion"], "answer": 0 },
        { "question": "Was ist ein 'Use Case'?", "options": ["Ein Anwendungsfall aus Sicht eines Akteurs", "Ein Koffer für den Laptop", "Ein Programmierfehler", "Ein Testfall"], "answer": 0 },
        { "question": "Was bedeutet eine '1..n' Beziehung im ER-Modell?", "options": ["Einem Datensatz stehen beliebig viele andere gegenüber", "Ein Datensatz steht genau einem anderen gegenüber", "Keine Beziehung", "Ein Fehler in der Datenbank"], "answer": 0 },
        { "question": "Was ist eine EPK (Ereignisgesteuerte Prozesskette)?", "options": ["Modellierung von Geschäftsprozessen", "Ein Programmierstandard", "Ein Netzwerkprotokoll", "Ein Verschlüsselungsverfahren"], "answer": 0 },
        { "question": "Welche Farben/Formen sind typisch für eine EPK?", "options": ["Sechsecke für Ereignisse, abgerundete Rechtecke für Funktionen", "Kreise für alles", "Nur Quadrate", "Dreiecke für Entscheidungen"], "answer": 0 },
        { "question": "Was ist ein 'Akteur' im Use-Case-Diagramm?", "options": ["Eine Rolle, die mit dem System interagiert", "Ein Schauspieler", "Der Programmierer", "Die Hardware"], "answer": 0 },
        { "question": "Was bedeutet 'Vererbung' im Klassendiagramm?", "options": ["Unterklasse übernimmt Eigenschaften der Oberklasse", "Löschen von Daten", "Kopieren von Code", "Sichern der Datenbank"], "answer": 0 },
        { "question": "Was ist ein ER-Modell (Entity-Relationship-Modell)?", "options": ["Modell zur Datenbankgestaltung", "Ein Modell für Flugzeuge", "Ein Netzwerkplan", "Ein Programmierstil"], "answer": 0 },
        { "question": "Was ist ein 'Attribut' in einem ER-Modell?", "options": ["Eine Eigenschaft einer Entität (z.B. Name)", "Eine Verknüpfung", "Der Primärschlüssel allein", "Ein Tabellenname"], "answer": 0 },
        { "question": "Was ist eine 'Kardinalität'?", "options": ["Mengenmäßige Angabe der Beziehung (1:1, 1:n, n:m)", "Die Farbe eines Diagramms", "Die Anzahl der Programmierer", "Ein mathematischer Fehler"], "answer": 0 },
        { "question": "Was stellt ein Zustandsdiagramm dar?", "options": ["Verhalten eines Objekts über seine Lebenszeit", "Die Hierarchie der Chefs", "Den Speicherplatzbedarf", "Die Netzwerkauslastung"], "answer": 0 },
        { "question": "Was ist eine 'Assoziation' im Klassendiagramm?", "options": ["Eine einfache Beziehung zwischen zwei Klassen", "Ein Verein", "Ein Fehler", "Ein Datentyp"], "answer": 0 },
        { "question": "Was ist eine 'Komposition'?", "options": ["Starke Form der Aggregation (Teile existieren nicht ohne Ganzes)", "Ein Musikstück", "Das Zusammenfügen von Code", "Ein Diagrammtyp"], "answer": 0 },
        { "question": "Welches Element startet eine EPK?", "options": ["Ein Ereignis", "Eine Funktion", "Ein logischer Operator", "Ein Pfeil"], "answer": 0 },
        { "question": "Was bedeutet 'XOR' in einer EPK?", "options": ["Exklusives Oder (genau einer von mehreren Wegen)", "Und/Oder gleichzeitig", "Ein Fehler", "X-beliebiger Operator"], "answer": 0 },
        { "question": "Was ist ein 'Primärschlüssel'?", "options": ["Eindeutiges Identifikationsmerkmal eines Datensatzes", "Der wichtigste Schlüssel im Büro", "Das Passwort für die Datenbank", "Der Name der Tabelle"], "answer": 0 },
        { "question": "Was ist ein 'Fremdschlüssel'?", "options": ["Verweis auf einen Primärschlüssel einer anderen Tabelle", "Ein Schlüssel von einem Gast", "Ein verschlüsselter Datensatz", "Ein falsches Passwort"], "answer": 0 }
      ]
    },
    {
      "title": "Logik und Fehlersuche",
      "id": "logik",
      "description": "Datentypen, Kontrollstrukturen, Operatoren und Debugging.",
      "priority": "hoch",
      "questions": [
        { "question": "Welcher Datentyp speichert ganze Zahlen?", "options": ["Integer", "String", "Boolean", "Float"], "answer": 0 },
        { "question": "Was speichert ein 'Boolean'?", "options": ["Wahrheitswerte (True/False)", "Texte", "Große Kommazahlen", "Datumswerte"], "answer": 0 },
        { "question": "Was ist eine 'if-else' Struktur?", "options": ["Eine bedingte Verzweigung", "Eine Endlosschleife", "Ein Datentyp", "Eine Fehlermeldung"], "answer": 0 },
        { "question": "Was macht eine 'for-Schleife'?", "options": ["Wiederholt Code eine bestimmte Anzahl oft", "Prüft nur eine Bedingung", "Beendet das Programm", "Sichert Daten"], "answer": 0 },
        { "question": "Welcher Operator steht für 'logisches UND' in vielen Sprachen?", "options": ["&&", "||", "!", "=="], "answer": 0 },
        { "question": "Was ist ein 'Array'?", "options": ["Eine Datenstruktur zur Speicherung mehrerer Werte gleichen Typs", "Ein einzelner Buchstabe", "Ein Virus", "Ein Monitor"], "answer": 0 },
        { "question": "Was bedeutet 'Debugging'?", "options": ["Fehlersuche und -behebung im Programmcode", "Neues Programm schreiben", "Computer sauber machen", "Viren verbreiten"], "answer": 0 },
        { "question": "Was ist ein 'Breakpoint'?", "options": ["Ein Haltepunkt im Code für die Fehlersuche", "Eine kaputte Stelle im Programm", "Das Ende des Arbeitstages", "Ein Tastaturbefehl"], "answer": 0 },
        { "question": "Was ist ein 'Syntaxfehler'?", "options": ["Verstoß gegen die Grammatikregeln der Programmiersprache", "Ein logischer Denkfehler", "Ein Hardwaredefekt", "Ein falsches Passwort"], "answer": 0 },
        { "question": "Was ist ein 'Laufzeitfehler' (Runtime Error)?", "options": ["Fehler, der erst während der Ausführung auftritt", "Ein Fehler beim Tippen", "Ein langsamer Computer", "Ein Fehler im Handbuch"], "answer": 0 },
        { "question": "Was bewirkt der Modulo-Operator (%)?", "options": ["Berechnet den Rest einer Division", "Berechnet Prozente", "Multipliziert Zahlen", "Löscht Variablen"], "answer": 0 },
        { "question": "Was ist ein 'Schreibtischtest'?", "options": ["Manuelles Durchgehen von Code mit Beispieldaten", "Prüfen, ob der Schreibtisch stabil ist", "Ein automatischer Virentest", "Ein Test am PC"], "answer": 0 },
        { "question": "Was bedeutet 'Inkrementieren'?", "options": ["Erhöhen eines Wertes (meist um 1)", "Verringern eines Wertes", "Löschen eines Wertes", "Kopieren eines Wertes"], "answer": 0 },
        { "question": "Was ist eine 'Endlosschleife'?", "options": ["Eine Schleife, deren Abbruchbedingung nie eintritt", "Eine sehr lange Schleife", "Ein Kreis im Diagramm", "Eine Schleife für Musik"], "answer": 0 },
        { "question": "Was ist 'Pseudocode'?", "options": ["Sprachnahe Beschreibung von Algorithmen ohne feste Syntax", "Falscher Code", "Verschlüsselter Code", "Code für Hacker"], "answer": 0 },
        { "question": "Was ist ein 'String'?", "options": ["Eine Zeichenkette (Text)", "Ein Unterwäschestück", "Ein Kabel", "Eine kleine Zahl"], "answer": 0 },
        { "question": "Was bewirkt 'Step-over' beim Debugging?", "options": ["Nächste Zeile ausführen, ohne in Funktionen zu springen", "Programm ganz beenden", "Fehler ignorieren", "Funktion löschen"], "answer": 0 },
        { "question": "Was ist eine 'Konstante'?", "options": ["Ein Wert, der sich während der Laufzeit nicht ändert", "Ein Wert, der sich ständig ändert", "Ein fester Mitarbeiter", "Eine Fehlermeldung"], "answer": 0 },
        { "question": "Was ist ein 'Compiler'?", "options": ["Programm, das Quellcode in Maschinensprache übersetzt", "Ein Texteditor", "Ein Antivirenprogramm", "Ein Betriebssystem"], "answer": 0 },
        { "question": "Welche logische Verknüpfung ist nur wahr, wenn BEIDE Bedingungen wahr sind?", "options": ["AND (UND)", "OR (ODER)", "NOT (NICHT)", "XOR"], "answer": 0 }
      ]
    },
    {
      "title": "Qualitätssicherung",
      "id": "qs",
      "description": "Testverfahren, Datenschutz by Design und Versionsverwaltung.",
      "priority": "mittel",
      "questions": [
        { "question": "Was ist ein 'Unit Test'?", "options": ["Test einzelner kleinster Komponenten (z.B. Funktionen)", "Test des gesamten Systems", "Test durch den Endkunden", "Ein Test der Hardware"], "answer": 0 },
        { "question": "Was versteht man unter 'Blackbox-Testing'?", "options": ["Test ohne Kenntnis des internen Programmcodes", "Test in einem dunklen Raum", "Test der Hardware-Box", "Ein geheimer Test"], "answer": 0 },
        { "question": "Was ist 'Whitebox-Testing'?", "options": ["Test mit Kenntnis und Fokus auf den internen Code", "Test weißer Computer", "Ein sehr einfacher Test", "Test der Benutzeroberfläche"], "answer": 0 },
        { "question": "Was ist 'Git'?", "options": ["Ein verteiltes Versionsverwaltungssystem", "Ein Programmiersprache", "Ein Hosting-Anbieter", "Ein Betriebssystem"], "answer": 0 },
        { "question": "Was macht ein 'Commit' in Git?", "options": ["Speichert Änderungen lokal im Repository", "Löscht den Code", "Sendet Code an den Server", "Lädt Code vom Server"], "answer": 0 },
        { "question": "Was bedeutet 'Privacy by Design'?", "options": ["Datenschutz bereits bei der Entwicklung berücksichtigen", "Daten besonders hübsch gestalten", "Datenschutz erst am Ende prüfen", "Kein Datenschutz"], "answer": 0 },
        { "question": "Was ist ein 'Integrationstest'?", "options": ["Test des Zusammenspiels mehrerer Komponenten", "Test eines neuen Mitarbeiters", "Test im Ausland", "Test der Stromversorgung"], "answer": 0 },
        { "question": "Was ist ein 'Systemtest'?", "options": ["Test des vollständigen Systems gegen die Anforderungen", "Ein Test des Betriebssystems", "Ein Test nur für Administratoren", "Ein kurzer Funktionstest"], "answer": 0 },
        { "question": "Was bedeutet 'Pull' in Git?", "options": ["Änderungen vom Server herunterladen und zusammenführen", "Code hochladen", "Code löschen", "Einen Fehler melden"], "answer": 0 },
        { "question": "Was ist ein 'Code Review'?", "options": ["Gegenseitiges Prüfen von Code durch andere Entwickler", "Ein Rückblick auf alte Projekte", "Das Kompilieren von Code", "Das Schreiben von Kommentaren"], "answer": 0 },
        { "question": "Was ist 'Refactoring'?", "options": ["Strukturverbesserung von Code ohne Verhaltensänderung", "Neuschreiben der kompletten Software", "Hinzufügen neuer Features", "Fehlersuche"], "answer": 0 },
        { "question": "Was versteht man unter 'Regressionstest'?", "options": ["Wiederholung von Tests nach Änderungen zur Sicherstellung alter Funktionen", "Ein Test für mathematische Regression", "Ein sehr schlechter Test", "Ein Test der Hardware"], "answer": 0 },
        { "question": "Was ist 'Privacy by Default'?", "options": ["Werkseinstellungen sind so datenschutzfreundlich wie möglich", "Datenschutz ist optional", "Alle Daten sind öffentlich", "Es gibt keinen Standard"], "answer": 0 },
        { "question": "Was ist 'Alpha-Testing'?", "options": ["Erste Testphase, meist intern durch Entwickler", "Test durch Millionen von Kunden", "Der finale Test", "Ein Test von Hardware-Prototypen"], "answer": 0 },
        { "question": "Was ist 'Beta-Testing'?", "options": ["Testphase durch ausgewählte Endnutzer vor Release", "Der erste Test überhaupt", "Ein Test der nur nachts läuft", "Ein Test für Profis"], "answer": 0 },
        { "question": "Was bedeutet 'Push' in Git?", "options": ["Lokale Änderungen an einen Remote-Server senden", "Code löschen", "Hilfe anfordern", "Programm starten"], "answer": 0 },
        { "question": "Was ist ein 'Repository'?", "options": ["Ein Speicherort für Projektdateien und deren Historie", "Ein spezieller Computer", "Ein Programmierfehler", "Ein Dokumentenordner"], "answer": 0 },
        { "question": "Was ist 'Lasttest'?", "options": ["Prüfung des Systems unter hoher Belastung", "Wiegen der Hardware", "Der letzte Test vor dem Urlaub", "Test der Stromkabel"], "answer": 0 },
        { "question": "Was ist 'Usability-Testing'?", "options": ["Test der Benutzerfreundlichkeit", "Test der Geschwindigkeit", "Test der Sicherheit", "Test der Datenbank"], "answer": 0 },
        { "question": "Was ist ein 'Bug-Report'?", "options": ["Dokumentation eines gefundenen Fehlers", "Ein Bericht über Insekten", "Eine neue Programmfunktion", "Ein Werbebrief"], "answer": 0 }
      ]
    }
  ]
});
