quizData.chapters.push({
  "title": "Lernfeld 6 bis 9: Service und Sicherheit",
  "priority": 6,
  "subsections": [
    {
      "title": "Service und Support",
      "id": "support",
      "description": "Ticketsysteme, ITIL-Basics, SLAs und Kommunikation.",
      "priority": "mittel",
      "questions": [
        { "question": "Was ist der Unterschied zwischen einem 'Incident' und einem 'Problem' (ITIL)?", "options": ["Ein Incident ist eine akute Störung, ein Problem die unbekannte Ursache", "Es gibt keinen Unterschied", "Ein Problem ist kleiner als ein Incident", "Ein Incident betrifft nur Hardware"], "answer": 0 },
        { "question": "Was beschreibt ein 'SLA' (Service Level Agreement)?", "options": ["Vereinbarung über die Dienstgüte (z.B. Reaktionszeit)", "Ein Kaufvertrag für Software", "Ein Arbeitsvertrag", "Ein Sicherheitszertifikat"], "answer": 0 },
        { "question": "Was ist 'First-Level-Support'?", "options": ["Erste Anlaufstelle für alle Anfragen (einfache Lösungen)", "Die Geschäftsleitung", "Spezialisten für Datenbanken", "Externe Berater"], "answer": 0 },
        { "question": "Was bedeutet 'Eskalation' im Support?", "options": ["Weitergabe eines Tickets an eine höhere Fachinstanz", "Wütend werden am Telefon", "Löschen eines Tickets", "Abschluss eines Projekts"], "answer": 0 },
        { "question": "Was ist ein 'Ticket-System'?", "options": ["Software zur Erfassung und Verwaltung von Support-Anfragen", "Ein System zum Drucken von Eintrittskarten", "Ein Fahrkartenautomat", "Ein Viren-Scanner"], "answer": 0 },
        { "question": "Was bedeutet 'Aktives Zuhören'?", "options": ["Dem Gegenüber volle Aufmerksamkeit schenken und Signale geben", "Einfach nur schweigend zuhören", "Währenddessen E-Mails schreiben", "Den Kunden unterbrechen"], "answer": 0 },
        { "question": "Was ist eine 'Wissensdatenbank' (Knowledge Base) im Support?", "options": ["Sammlung bekannter Fehler und deren Lösungen", "Ein Verzeichnis aller Mitarbeiter", "Ein Handbuch für den Chef", "Eine Liste aller Passwörter"], "answer": 0 },
        { "question": "Was ist 'Remote Support'?", "options": ["Fernwartung des Systems über das Netzwerk", "Support im Wald", "Support nur per Brief", "Hardware-Tausch vor Ort"], "answer": 0 },
        { "question": "Was ist ein 'SLA-Bruch'?", "options": ["Nichteinhaltung der vereinbarten Service-Ziele", "Ein kaputtes Kabel", "Ein Fehler in der Software", "Die Kündigung des Vertrags"], "answer": 0 },
        { "question": "Was bedeutet 'Incident Management'?", "options": ["Schnellstmögliche Wiederherstellung des Services", "Suche nach der tiefen Ursache", "Verkauf von Software", "Planung neuer Server"], "answer": 0 },
        { "question": "Was ist 'Problem Management'?", "options": ["Dauerhafte Beseitigung der Ursache von Störungen", "Schnelles Fixen von Fehlern", "Ignorieren von Kundenbeschwerden", "Verteilung von Aufgaben"], "answer": 0 },
        { "question": "Was ist 'Change Management' (ITIL)?", "options": ["Standardisierter Prozess zur Durchführung von Änderungen", "Austausch von Mitarbeitern", "Ändern des Passworts", "Kauf neuer Hardware"], "answer": 0 },
        { "question": "Was ist eine 'Offene Frage'?", "options": ["Frage, die nicht mit Ja/Nein beantwortet werden kann", "Eine Frage ohne Antwort", "Eine verbotene Frage", "Eine Frage an das Team"], "answer": 0 },
        { "question": "Wofür steht 'ITIL'?", "options": ["Information Technology Infrastructure Library", "IT Interface Layout", "International Tech Industry List", "Integrated Technology Information Link"], "answer": 0 },
        { "question": "Was ist 'Second-Level-Support'?", "options": ["Fachabteilung für komplexere Probleme", "Der Empfang", "Die Buchhaltung", "Der Kunde selbst"], "answer": 0 },
        { "question": "Was ist 'Verfügbarkeit' in einem SLA?", "options": ["Prozentuale Zeit, in der ein System betriebsbereit ist", "Die Anzahl der Mitarbeiter", "Der Preis des Systems", "Die Farbe des Gehäuses"], "answer": 0 },
        { "question": "Was bedeutet 'Reaktionszeit'?", "options": ["Zeit zwischen Ticketeingang und erster Bearbeitung", "Zeit bis der Fehler behoben ist", "Zeit bis der Admin Kaffee hat", "Dauer des Telefonats"], "answer": 0 },
        { "question": "Was ist eine 'Eskalationsmatrix'?", "options": ["Plan, wer wann bei welchem Problem informiert wird", "Ein Film mit Keanu Reeves", "Eine mathematische Formel", "Eine Liste von Hardware"], "answer": 0 },
        { "question": "Was ist ein 'Service Request'?", "options": ["Standardanfrage (z.B. neues Passwort, Softwarewunsch)", "Ein schwerer Systemfehler", "Ein Hardwarebrand", "Ein Hackerangriff"], "answer": 0 },
        { "question": "Warum sind Fragetechniken im Support wichtig?", "options": ["Um das Problem präzise und schnell einzugrenzen", "Um den Kunden zu ärgern", "Um Zeit zu schinden", "Um schlau zu wirken"], "answer": 0 }
      ]
    },
    {
      "title": "IT Sicherheit",
      "id": "security",
      "description": "Schutzziele (CIA), Verschlüsselung und Härtung.",
      "priority": "sehr hoch",
      "questions": [
        { "question": "Wofür steht das 'C' in den Schutzzielen CIA?", "options": ["Confidentiality (Vertraulichkeit)", "Consistency", "Control", "Cloud"], "answer": 0 },
        { "question": "Wofür steht das 'I' in CIA?", "options": ["Integrity (Integrität/Unversehrtheit)", "Information", "Infrastructure", "Internet"], "answer": 0 },
        { "question": "Wofür steht das 'A' in CIA?", "options": ["Availability (Verfügbarkeit)", "Access", "Authentication", "Accounting"], "answer": 0 },
        { "question": "Was ist 'symmetrische Verschlüsselung'?", "options": ["Gleicher Schlüssel für Ver- und Entschlüsselung", "Unterschiedliche Schlüssel", "Verschlüsselung nur von Text", "Ganz ohne Schlüssel"], "answer": 0 },
        { "question": "Was ist 'asymmetrische Verschlüsselung'?", "options": ["Public Key zum Verschlüsseln, Private Key zum Entschlüsseln", "Ein Schlüssel für alles", "Nur für Linux-Systeme", "Besonders schnelle Methode"], "answer": 0 },
        { "question": "Was ist ein 'Hash-Verfahren'?", "options": ["Erzeugung einer Prüfsumme (Einwegfunktion)", "Eine Verschlüsselung", "Ein Komprimierungstool", "Ein Dateisystem"], "answer": 0 },
        { "question": "Was bewirkt eine 'Digitale Signatur'?", "options": ["Sicherstellung der Authentizität und Integrität", "Verschlüsselung des Inhalts", "Schnellerer Versand", "Löschen von Daten"], "answer": 0 },
        { "question": "Was ist 'Salting' bei Passwörtern?", "options": ["Hinzufügen eines zufälligen Wertes vor dem Hashen", "Passwort mit Salz bestreuen", "Passwort kürzen", "Passwort doppelt eingeben"], "answer": 0 },
        { "question": "Was bedeutet 'Systemhärtung' (Hardening)?", "options": ["Deaktivieren unnötiger Dienste und Schließen von Ports", "Gehäuse aus Stahl bauen", "CPU übertakten", "Monitor heller stellen"], "answer": 0 },
        { "question": "Was ist eine 'Firewall'?", "options": ["Sicherheitssystem, das Netzwerkverkehr filtert", "Eine brennende Wand im Serverraum", "Ein Antiviren-Programm", "Ein spezielles Kabel"], "answer": 0 },
        { "question": "Was ist ein 'Virenschutz'?", "options": ["Software zur Erkennung und Abwehr von Schadprogrammen", "Ein Mundschutz für den Admin", "Eine Firewall", "Ein Backup"], "answer": 0 },
        { "question": "Was ist ein 'Zertifikat' (SSL/TLS)?", "options": ["Digitaler Identitätsnachweis für Server/Webseiten", "Eine Urkunde für den Admin", "Ein Programmfehler", "Eine Hardware-Garantie"], "answer": 0 },
        { "question": "Wofür wird 'AES' verwendet?", "options": ["Symmetrische Verschlüsselung", "Asymmetrische Verschlüsselung", "Hashen von Dateien", "Webdesign"], "answer": 0 },
        { "question": "Wofür wird 'RSA' verwendet?", "options": ["Asymmetrische Verschlüsselung", "Symmetrische Verschlüsselung", "Stromversorgung", "Monitoranschluss"], "answer": 0 },
        { "question": "Was ist 'Zwei-Faktor-Authentifizierung' (2FA)?", "options": ["Anmeldung mit zwei unabhängigen Komponenten", "Zwei Passwörter nacheinander", "Anmeldung durch zwei Personen", "Ein sehr langes Passwort"], "answer": 0 },
        { "question": "Was ist das Ziel der 'Integrität'?", "options": ["Daten dürfen nicht unbemerkt verändert werden", "Daten müssen geheim bleiben", "Daten müssen immer erreichbar sein", "Daten müssen gelöscht werden"], "answer": 0 },
        { "question": "Was ist ein 'Intrusion Detection System' (IDS)?", "options": ["System zur Erkennung von Einbrüchen/Angriffen", "Eine Alarmanlage an der Tür", "Ein Viren-Scanner", "Ein Backup-Programm"], "answer": 0 },
        { "question": "Was bedeutet 'Least Privilege Prinzip'?", "options": ["Benutzer erhalten nur so viele Rechte wie nötig", "Jeder darf alles", "Der Admin hat keine Rechte", "Rechte werden verlost"], "answer": 0 },
        { "question": "Was ist 'Verschlüsselung am Ruheort' (Encryption at Rest)?", "options": ["Verschlüsselung von gespeicherten Daten (z.B. Festplatte)", "Verschlüsselung während der Übertragung", "Verschlüsselung im RAM", "Ausschalten des PCs"], "answer": 0 },
        { "question": "Was ist ein 'Zero-Day-Exploit'?", "options": ["Angriff auf eine bisher unbekannte Sicherheitslücke", "Ein Angriff am ersten Tag im Monat", "Ein sehr alter Virus", "Ein Angriff der 24 Stunden dauert"], "answer": 0 }
      ]
    },
    {
      "title": "Angriff und Verteidigung",
      "id": "attacks",
      "description": "Malware, Social Engineering und Passworthierarchie.",
      "priority": "hoch",
      "questions": [
        { "question": "Was ist 'Social Engineering'?", "options": ["Manipulation von Menschen, um an Informationen zu gelangen", "Programmierung von sozialen Netzwerken", "Bau von Brücken", "Einrichten von Benutzerkonten"], "answer": 0 },
        { "question": "Was ist 'Phishing'?", "options": ["Betrügerische E-Mails zum Stehlen von Zugangsdaten", "Angeln im Internet", "Ein neuer Browser", "Ein Netzwerkprotokoll"], "answer": 0 },
        { "question": "Was ist 'Ransomware'?", "options": ["Schadsoftware, die Daten verschlüsselt und Lösegeld fordert", "Kostenlose Software", "Software zur Speicheroptimierung", "Ein Betriebssystem"], "answer": 0 },
        { "question": "Was ist ein 'Trojaner'?", "options": ["Schadprogramm, das sich als nützliche Software tarnt", "Ein schnelles Pferd", "Ein Virus, der sich selbst repliziert", "Ein Hardware-Defekt"], "answer": 0 },
        { "question": "Was ist ein 'Wurm'?", "options": ["Schadprogramm, das sich selbstständig über das Netz verbreitet", "Ein Programm, das Dateien frisst", "Ein kleines Hardware-Teil", "Ein spezielles Kabel"], "answer": 0 },
        { "question": "Was ist eine 'DDoS-Attacke'?", "options": ["Überlastung eines Dienstes durch massenhafte Anfragen", "Löschen der Datenbank", "Diebstahl von Passwörtern", "Ein Virus auf dem Handy"], "answer": 0 },
        { "question": "Was ist ein 'Man-in-the-Middle-Angriff'?", "options": ["Angreifer schaltet sich unbemerkt in Kommunikation ein", "Ein Administrator-Fehler", "Zwei Leute an einem PC", "Ein Hardware-Switch"], "answer": 0 },
        { "question": "Was beschreibt 'Brute Force'?", "options": ["Ausprobieren aller möglichen Passwort-Kombinationen", "Ein starker Magnet im Serverraum", "Gewalt gegen Hardware", "Besonders schneller Download"], "answer": 0 },
        { "question": "Was ist 'Pretexting'?", "options": ["Erfinden eines Szenarios beim Social Engineering", "Testen von Texten", "Ein Programmfehler", "Ein Backup-Verfahren"], "answer": 0 },
        { "question": "Was ist 'Tailgating'?", "options": ["Unbefugtes Folgen einer befugten Person in gesicherte Bereiche", "Hinterherfahren im Auto", "Ein Computer-Spiel", "Ein Netzwerk-Problem"], "answer": 0 },
        { "question": "Was ist 'Keylogging'?", "options": ["Aufzeichnen aller Tastatureingaben", "Ein neues Passwort-System", "Ein mechanisches Problem der Tastatur", "Ein Login-Verfahren"], "answer": 0 },
        { "question": "Was ist 'Spyware'?", "options": ["Software, die Nutzeraktivitäten unbemerkt ausspioniert", "Ein Programm für Detektive", "Eine Firewall", "Ein Spiel"], "answer": 0 },
        { "question": "Was ist 'SQL Injection'?", "options": ["Einschleusen von bösartigen Datenbankbefehlen", "Spritzen von Wasser in den PC", "Ein Datenbank-Update", "Ein schnelles Backup"], "answer": 0 },
        { "question": "Wie sollte ein sicheres Passwort beschaffen sein?", "options": ["Lang, komplex (Sonderzeichen, Zahlen, Groß/Klein)", "Nur der Vorname", "123456", "In einem Buch notiert"], "answer": 0 },
        { "question": "Wofür steht 'MFA'?", "options": ["Multi-Faktor-Authentifizierung", "Main Frame Access", "Multi Fiber Area", "Mobile File Archive"], "answer": 0 },
        { "question": "Was ist 'Botnet'?", "options": ["Netzwerk aus infizierten Rechnern unter fremder Kontrolle", "Ein Netzwerk für Roboter", "Ein sehr schnelles Internet", "Ein Forum für Hilfe"], "answer": 0 },
        { "question": "Was ist 'Adware'?", "options": ["Software, die unerwünscht Werbung einblendet", "Software für Grafik", "Ein Virenscanner", "Kostenlose Software"], "answer": 0 },
        { "question": "Was ist ein 'Exploit'?", "options": ["Ausnutzen einer Schwachstelle", "Ein Export von Daten", "Ein Programm zum Packen", "Eine Hardware-Erweiterung"], "answer": 0 },
        { "question": "Was ist 'Shoulder Surfing'?", "options": ["Beobachten der Passworteingabe über die Schulter", "Surfen im Stehen", "Ein Sport", "Ein Programmfehler"], "answer": 0 },
        { "question": "Was ist 'Honey Pot'?", "options": ["Ein absichtlich unsicheres System zum Anlocken von Angreifern", "Ein Topf Honig für den Admin", "Ein Backup-Server", "Ein süßer Virus"], "answer": 0 }
      ]
    },
    {
      "title": "Übergabe und Abschluss",
      "id": "closing",
      "description": "Rollout-Strategien, Abnahmeprotokoll und Dokumentation.",
      "priority": "hoch",
      "questions": [
        { "question": "Was ist ein 'Big Bang Rollout'?", "options": ["Gleichzeitige Einführung des Systems für alle Nutzer", "Ein explodierender Server", "Ein sehr lautes Programm", "Ein stufenweiser Prozess"], "answer": 0 },
        { "question": "Was gehört zwingend in ein 'Abnahmeprotokoll'?", "options": ["Datum, Unterschriften, festgestellte Mängel", "Die IP-Adresse des Servers", "Die Farbe der Kabel", "Ein Foto des Teams"], "answer": 0 },
        { "question": "Was ist eine 'Benutzereinweisung'?", "options": ["Schulung der Anwender im Umgang mit dem neuen System", "Den User in den Keller schicken", "Das Handbuch wegwerfen", "Ein Passwort vergeben"], "answer": 0 },
        { "question": "Was ist der Zweck der 'Benutzerdokumentation'?", "options": ["Hilfe für den Anwender zur Bedienung der Software", "Code-Beschreibung für Programmierer", "Ein geheimes Dokument", "Eine Liste aller Fehler"], "answer": 0 },
        { "question": "Was bedeutet 'Soll-Ist-Vergleich'?", "options": ["Gegenüberstellung von geplanten Zielen und erreichtem Ergebnis", "Vergleich von zwei Computern", "Ein Blick in die Zukunft", "Ein Buchhaltungsfehler"], "answer": 0 },
        { "question": "Was ist eine 'Nachkalkulation'?", "options": ["Ermittlung der tatsächlichen Kosten nach Projektabschluss", "Rechnen während der Arbeit", "Eine Schätzung der Kosten", "Das Bezahlen der Rechnung"], "answer": 0 },
        { "question": "Was ist ein 'stufenweiser Rollout'?", "options": ["Einführung in Etappen (z.B. nach Abteilungen)", "Treppensteigen mit Hardware", "Gleichzeitig für alle", "Gar kein Rollout"], "answer": 0 },
        { "question": "Was ist 'Projektdokumentation'?", "options": ["Vollständige Aufzeichnung des Projektverlaufs für die Nachwelt", "Nur das Lastenheft", "Ein paar Notizen auf Papier", "Der Code allein"], "answer": 0 },
        { "question": "Was ist die 'Gewährleistung' nach Projektabschluss?", "options": ["Gesetzliche Pflicht zur Mängelbeseitigung", "Freiwilliges Geschenk", "Ein neues Projekt", "Gibt es nicht"], "answer": 0 },
        { "question": "Was ist eine 'Abnahme'?", "options": ["Rechtliche Erklärung des Kunden, dass die Leistung erfüllt ist", "Das Gewicht des Servers reduzieren", "Den Computer ausschalten", "Den Preis senken"], "answer": 0 },
        { "question": "Was ist ein 'Wartungsvertrag'?", "options": ["Vereinbarung über laufende Betreuung nach Übergabe", "Ein Vertrag zum Putzen", "Ein Mietvertrag", "Eine Kündigung"], "answer": 0 },
        { "question": "Was bedeutet 'Go-Live'?", "options": ["Der Zeitpunkt der Inbetriebnahme des Systems", "Ein Konzert", "Ein Videospiel", "Der Feierabend"], "answer": 0 },
        { "question": "Was ist eine 'Systemdokumentation'?", "options": ["Technische Beschreibung der Installation und Konfiguration", "Ein Handbuch für Laien", "Ein Werbeprospekt", "Ein leeres Blatt"], "answer": 0 },
        { "question": "Was ist ein 'Projektabschlussbericht'?", "options": ["Zusammenfassende Bewertung des Projekterfolgs", "Ein kleiner Zettel", "Eine neue Rechnung", "Die Kündigung"], "answer": 0 },
        { "question": "Was ist 'Change Request' nach der Übergabe?", "options": ["Anfrage für eine nachträgliche Änderung am System", "Ein neuer Admin", "Ein Hardware-Tausch", "Ein Fehlerbericht"], "answer": 0 },
        { "question": "Was ist 'Lesson Learned'?", "options": ["Analyse von Erfahrungen im Projekt für die Zukunft", "Hausaufgaben machen", "Ein Test für den Chef", "Eine Bestrafung"], "answer": 0 },
        { "question": "Welche Mängelart liegt vor, wenn eine Funktion fehlt?", "options": ["Sachmangel", "Rechtsmangel", "Farbmangel", "Gibt es nicht"], "answer": 0 },
        { "question": "Was ist ein 'Pilotprojekt'?", "options": ["Testlauf des Systems in einem kleinen, kontrollierten Bereich", "Ein Projekt für Flugzeuge", "Ein sehr teures Projekt", "Das erste Projekt überhaupt"], "answer": 0 },
        { "question": "Was ist ein 'Soll-Zustand'?", "options": ["Das angestrebte Ziel laut Planung", "Der aktuelle Stand", "Ein kaputtes System", "Das Ende der Welt"], "answer": 0 },
        { "question": "Was ist der Sinn einer Abschlussbesprechung?", "options": ["Reflexion des Projekts und offizielle Entlastung des Teams", "Gemeinsames Pizzaessen (nur)", "Fehlersuche im Code", "Planung des Urlaubs"], "answer": 0 }
      ]
    }
  ]
});
