quizData.chapters.push({
  "title": "WiSo und Ergonomie",
  "priority": 7,
  "subsections": [
    {
      "title": "Arbeitsrecht und Sozialversicherung",
      "id": "arbeitsrecht",
      "description": "Arbeitsvertrag, Kündigungsschutz und die 5 Säulen der Sozialversicherung.",
      "priority": "hoch",
      "questions": [
        { "question": "Welche 5 Säulen bilden die gesetzliche Sozialversicherung in Deutschland?", "options": ["Kranken-, Renten-, Arbeitslosen-, Pflege-, Unfallversicherung", "Auto-, Haftpflicht-, Hausrat-, Lebens-, Rechtsschutz", "Renten-, Unfall-, Kranken-, Rechtsschutz-, Pflege", "Kranken-, Renten-, Lebens-, Arbeitslosen-, Haftpflicht"], "answer": 0 },
        { "question": "Wer ist der Träger der gesetzlichen Unfallversicherung?", "options": ["Berufsgenossenschaften", "Krankenkassen", "Bundesagentur für Arbeit", "Deutsche Rentenversicherung"], "answer": 0 },
        { "question": "Welche Sozialversicherung wird als einzige allein vom Arbeitgeber getragen?", "options": ["Unfallversicherung", "Rentenversicherung", "Krankenversicherung", "Pflegeversicherung"], "answer": 0 },
        { "question": "Wie lange ist die gesetzliche Kündigungsfrist während der Probezeit (idR)?", "options": ["2 Wochen", "4 Wochen", "3 Monate", "Gibt es nicht"], "answer": 0 },
        { "question": "Was besagt das Jugendarbeitsschutzgesetz (JArbSchG) zur täglichen Arbeitszeit?", "options": ["Maximal 8 Stunden (8,5 in Ausnahmen)", "Maximal 10 Stunden", "Beliebig", "Mindestens 6 Stunden"], "answer": 0 },
        { "question": "Welche Form muss ein Ausbildungsvertrag zwingend haben?", "options": ["Schriftform", "Mündlich reicht", "Textform (E-Mail)", "Notariell beglaubigt"], "answer": 0 },
        { "question": "Was ist der Unterschied zwischen ordentlicher und außerordentlicher Kündigung?", "options": ["Außerordentlich erfolgt fristlos aus wichtigem Grund", "Gibt keinen Unterschied", "Ordentlich ist immer fristlos", "Außerordentlich ist nur für Azubis"], "answer": 0 },
        { "question": "Wann beginnt der Mutterschutz in der Regel vor der Entbindung?", "options": ["6 Wochen vorher", "2 Wochen vorher", "3 Monate vorher", "Gar nicht"], "answer": 0 },
        { "question": "Wer zahlt das Arbeitslosengeld I?", "options": ["Bundesagentur für Arbeit", "Rentenversicherung", "Krankenkasse", "Der letzte Arbeitgeber"], "answer": 0 },
        { "question": "Was ist die Beitragsbemessungsgrenze?", "options": ["Maximaler Lohnanteil, von dem Sozialbeiträge berechnet werden", "Mindestlohn", "Steuerfreibetrag", "Höchstgrenze für Überstunden"], "answer": 0 },
        { "question": "Welcher Grundsatz gilt bei der Finanzierung der meisten Sozialversicherungen?", "options": ["Paritätische Finanzierung (AG und AN teilen sich den Beitrag)", "Alleinfinanzierung durch den Staat", "Alleinfinanzierung durch den AN", "Spendenbasiert"], "answer": 0 },
        { "question": "Was ist ein 'qualifiziertes Arbeitszeugnis'?", "options": ["Zeugnis über Art, Dauer und Führung/Leistung", "Nur Bestätigung der Dauer", "Ein Zeugnis mit Foto", "Ein Zeugnis nur für Manager"], "answer": 0 },
        { "question": "Was ist das Ziel der gesetzlichen Rentenversicherung?", "options": ["Sicherung des Lebensstandards im Alter", "Finanzierung von Urlauben", "Krankheitskosten decken", "Arbeitsplätze schaffen"], "answer": 0 },
        { "question": "Ab wie vielen Mitarbeitern gilt der allgemeine Kündigungsschutz?", "options": ["Mehr als 10 Vollzeitmitarbeiter", "Ab dem 1. Mitarbeiter", "Ab 50 Mitarbeitern", "Ab 100 Mitarbeitern"], "answer": 0 },
        { "question": "Was ist eine 'Abmahnung'?", "options": ["Hinweis auf Fehlverhalten mit Androhung von Konsequenzen", "Eine sofortige Kündigung", "Eine Gehaltserhöhung", "Ein Lob"], "answer": 0 },
        { "question": "Was ist das 'Umlageverfahren' in der Rentenversicherung?", "options": ["Aktuelle Beitragszahler finanzieren aktuelle Rentner", "Jeder spart für sich selbst", "Der Staat zahlt alles aus Steuern", "Geld wird in Gold angelegt"], "answer": 0 },
        { "question": "Was ist der Mindesturlaubsanspruch pro Jahr bei einer 5-Tage-Woche (BUrlG)?", "options": ["20 Tage", "24 Tage", "15 Tage", "30 Tage"], "answer": 0 },
        { "question": "Welche Versicherung springt bei Berufskrankheiten ein?", "options": ["Unfallversicherung", "Krankenversicherung", "Pflegeversicherung", "Arbeitslosenversicherung"], "answer": 0 },
        { "question": "Was bedeutet 'Bruttolohn'?", "options": ["Lohn vor Abzug von Steuern und Sozialbeiträgen", "Lohn nach allen Abzügen", "Lohn inklusive Spesen", "Lohn ohne Urlaubsanspruch"], "answer": 0 },
        { "question": "Wofür steht 'ELStAM'?", "options": ["Elektronische Lohnsteuerabzugsmerkmale", "Einfache Lohn-Steuer-Anmeldung", "Elektronisches Mitarbeiter-Archiv", "Effizientes Lohn-System"], "answer": 0 }
      ]
    },
    {
      "title": "Mitbestimmung und Tarifrecht",
      "id": "mitbestimmung",
      "description": "Betriebsrat, JAV und Tarifverträge.",
      "priority": "mittel",
      "questions": [
        { "question": "Ab wie vielen wahlberechtigten Arbeitnehmern kann ein Betriebsrat gewählt werden?", "options": ["5 ständige wahlberechtigte Arbeitnehmer", "10 Arbeitnehmer", "50 Arbeitnehmer", "100 Arbeitnehmer"], "answer": 0 },
        { "question": "Was ist die Aufgabe der JAV (Jugend- und Auszubildendenvertretung)?", "options": ["Vertretung der Belange von Azubis und Jugendlichen", "Kündigung von Azubis", "Festlegung der Gehälter", "Organisation der Weihnachtsfeier"], "answer": 0 },
        { "question": "Wer schließt einen Tarifvertrag ab?", "options": ["Gewerkschaften und Arbeitgeberverbände (oder Einzel-AG)", "Betriebsrat und Chef", "Der Staat und die Bürger", "Azubis und Ausbilder"], "answer": 0 },
        { "question": "Was bedeutet 'Tarifautonomie'?", "options": ["Staat darf nicht in Tarifverhandlungen eingreifen", "Jeder darf seinen Tarif selbst wählen", "Autos für Tarifbeschäftigte", "Automatische Gehaltserhöhung"], "answer": 0 },
        { "question": "Was ist ein 'Manteltarifvertrag'?", "options": ["Regelt langfristige Arbeitsbedingungen (Urlaub, Arbeitszeit)", "Regelt nur die Gehälter", "Ein Vertrag über Berufsbekleidung", "Ein Vertrag nur für den Winter"], "answer": 0 },
        { "question": "Was ist ein 'Lohn- und Gehaltstarifvertrag'?", "options": ["Regelt die Höhe der Vergütung (kurze Laufzeit)", "Regelt die Kündigungsfristen", "Regelt den Arbeitsschutz", "Gibt es nicht"], "answer": 0 },
        { "question": "Was ist ein 'Streik'?", "options": ["Gemeinsame Arbeitsniederlegung zur Durchsetzung von Forderungen", "Eine Pause", "Eine Kündigungswelle", "Ein technischer Defekt"], "answer": 0 },
        { "question": "Was ist die 'Friedenspflicht' während der Laufzeit eines Tarifvertrags?", "options": ["Es darf währenddessen nicht wegen Inhalten des Vertrags gestreikt werden", "Man muss nett zueinander sein", "Keine Kündigungen erlaubt", "Keine Überstunden"], "answer": 0 },
        { "question": "Was bedeutet 'Aussperrung'?", "options": ["Arbeitgeber verweigert Arbeitnehmern den Zutritt und zahlt keinen Lohn", "Einschließen der Mitarbeiter im Büro", "Kündigung aller Mitarbeiter", "Verbot von Überstunden"], "answer": 0 },
        { "question": "Was ist ein 'Betriebsvereinbarung'?", "options": ["Vertrag zwischen Arbeitgeber und Betriebsrat für den Betrieb", "Ein Vertrag zwischen zwei Firmen", "Ein Tarifvertrag", "Ein Arbeitsvertrag"], "answer": 0 },
        { "question": "Hat der Betriebsrat ein Mitbestimmungsrecht bei der Urlaubsplanung?", "options": ["Ja, bei der Aufstellung allgemeiner Urlaubsgrundsätze", "Nein, nie", "Nur bei Azubis", "Nur wenn der Chef zustimmt"], "answer": 0 },
        { "question": "Welche Organe der Mitbestimmung gibt es auf Unternehmensebene?", "options": ["Aufsichtsrat", "Betriebsrat", "Gewerkschaft", "Amtsgericht"], "answer": 0 },
        { "question": "Was ist ein 'Schlichtungsverfahren'?", "options": ["Versuch, einen Tarifkonflikt ohne Streik zu lösen", "Ein Gerichtsverfahren", "Ein Streitgespräch", "Eine Kündigung"], "answer": 0 },
        { "question": "Wer darf den Betriebsrat wählen (aktives Wahlrecht)?", "options": ["Alle Arbeitnehmer des Betriebs, die das 18. Lebensjahr vollendet haben", "Nur Gewerkschaftsmitglieder", "Nur deutsche Staatsbürger", "Nur die Chefetage"], "answer": 0 },
        { "question": "Was ist 'Mitwirkung' im Gegensatz zu 'Mitbestimmung'?", "options": ["Recht auf Information und Anhörung (schwächer als Mitbestimmung)", "Dasselbe", "Stärkeres Recht", "Gibt es nicht"], "answer": 0 },
        { "question": "Können im Arbeitsvertrag schlechtere Bedingungen als im Tarifvertrag stehen (Günstigkeitsprinzip)?", "options": ["Nein, außer sie sind für den Arbeitnehmer günstiger", "Ja, immer", "Nur mit Zustimmung des Staates", "Nur in der Probezeit"], "answer": 0 },
        { "question": "Was ist ein 'Wilder Streik'?", "options": ["Streik ohne Urabstimmung und Gewerkschaftsführung (unzulässig)", "Streik im Wald", "Besonders lauter Streik", "Streik für mehr Urlaub"], "answer": 0 },
        { "question": "Wofür steht 'DGB'?", "options": ["Deutscher Gewerkschaftsbund", "Digitaler Gesamt-Bund", "Daten-Garantie-Board", "Deutsch-Germanischer Bund"], "answer": 0 },
        { "question": "Was ist eine 'Urabstimmung'?", "options": ["Abstimmung der Gewerkschaftsmitglieder über einen Streik", "Wahl des Bundeskanzlers", "Wahl des Betriebsrats", "Abstimmung über das Mittagessen"], "answer": 0 },
        { "question": "Wie oft finden regelmäßige Betriebsratswahlen statt?", "options": ["Alle 4 Jahre", "Jedes Jahr", "Alle 10 Jahre", "Nur bei Bedarf"], "answer": 0 }
      ]
    },
    {
      "title": "Unternehmensformen",
      "id": "rechtsformen",
      "description": "GmbH, AG, Einzelunternehmen und Personengesellschaften.",
      "priority": "mittel",
      "questions": [
        { "question": "Was ist das Mindestkapital für die Gründung einer GmbH?", "options": ["25.000 Euro", "1 Euro", "50.000 Euro", "100.000 Euro"], "answer": 0 },
        { "question": "Wie hoch ist das Mindestkapital einer AG (Aktiengesellschaft)?", "options": ["50.000 Euro", "25.000 Euro", "100.000 Euro", "1.000.000 Euro"], "answer": 0 },
        { "question": "Wer haftet bei einer GmbH?", "options": ["Die Gesellschaft mit ihrem Geschäftsvermögen", "Die Gesellschafter mit ihrem Privatvermögen", "Niemand", "Nur der Geschäftsführer persönlich"], "answer": 0 },
        { "question": "Was kennzeichnet ein Einzelunternehmen?", "options": ["Inhaber haftet allein und unbeschränkt mit Privatvermögen", "Haftung ist auf 1000 Euro begrenzt", "Man braucht 3 Gründer", "Mindestkapital von 10.000 Euro"], "answer": 0 },
        { "question": "Was ist eine 'GmbH & Co. KG'?", "options": ["Eine Kommanditgesellschaft mit einer GmbH als Vollhafter", "Zwei Firmen, die sich ein Büro teilen", "Eine sehr sichere AG", "Ein Fehler im Handelsregister"], "answer": 0 },
        { "question": "Wofür steht 'oHG'?", "options": ["Offene Handelsgesellschaft", "Online-Handels-Gruppe", "Organisierte Haupt-Gesellschaft", "Ohne Haftung Gegründet"], "answer": 0 },
        { "question": "Was ist der Unterschied zwischen Komplementär und Kommanditist (KG)?", "options": ["Komplementär haftet voll, Kommanditist nur mit Einlage", "Dasselbe", "Kommanditist ist der Chef", "Komplementär ist nur Geldgeber"], "answer": 0 },
        { "question": "Was ist das 'Handelsregister'?", "options": ["Öffentliches Verzeichnis aller Kaufleute eines Bezirks", "Ein Buch mit Preisen", "Ein Telefonbuch", "Eine Liste von Kunden"], "answer": 0 },
        { "question": "Was ist eine 'Juristische Person'?", "options": ["Eine Organisation mit eigener Rechtspersönlichkeit (z.B. GmbH)", "Ein Richter", "Ein Anwalt", "Ein Mensch aus Fleisch und Blut"], "answer": 0 },
        { "question": "Was ist eine 'UG (haftungsbeschränkt)'?", "options": ["Mini-GmbH mit Startkapital ab 1 Euro", "Eine sehr große Firma", "Eine Firma ohne Steuern", "Eine Universität"], "answer": 0 },
        { "question": "Welches Organ hat die Aktiengesellschaft?", "options": ["Vorstand, Aufsichtsrat, Hauptversammlung", "Nur den Chef", "Betriebsrat und JAV", "Aufsichtsbehörde"], "answer": 0 },
        { "question": "Wer wählt bei der AG den Vorstand?", "options": ["Der Aufsichtsrat", "Die Aktionäre direkt", "Die Mitarbeiter", "Der Staat"], "answer": 0 },
        { "question": "Was ist 'Firmenwahrheit'?", "options": ["Name der Firma darf nicht irreführend sein", "Die Firma muss immer die Wahrheit sagen", "Der Gewinn muss echt sein", "Keine Werbung erlaubt"], "answer": 0 },
        { "question": "Was ist eine 'Genossenschaft'?", "options": ["Zusammenschluss zur Förderung der Mitglieder (z.B. Einkauf)", "Eine AG für Arme", "Ein Verein für Sport", "Eine staatliche Behörde"], "answer": 0 },
        { "question": "Was bedeutet 'unbeschränkte Haftung'?", "options": ["Haftung auch mit dem gesamten Privatvermögen", "Haftung nur mit dem Auto", "Haftung bis 1 Million Euro", "Keine Haftung"], "answer": 0 },
        { "question": "Welche Rechtsform eignet sich für Freiberufler (z.B. IT-Berater) ohne Kapital?", "options": ["Einzelunternehmen oder GbR", "AG", "GmbH", "KG"], "answer": 0 },
        { "question": "Wo wird eine GmbH eingetragen?", "options": ["Abteilung B des Handelsregisters", "Abteilung A des Handelsregisters", "Grundbuch", "Vereinsregister"], "answer": 0 },
        { "question": "Was ist die 'Hauptversammlung' bei einer AG?", "options": ["Versammlung der Aktionäre", "Treffen der Vorstände", "Sitzung des Betriebsrats", "Kantine"], "answer": 0 },
        { "question": "Was ist eine 'GbR'?", "options": ["Gesellschaft bürgerlichen Rechts", "Große bürgerliche Runde", "Gemeinsame büro Ressourcen", "Gibt es nicht mehr"], "answer": 0 },
        { "question": "Was ist die 'Publizitätspflicht'?", "options": ["Pflicht bestimmter Firmen, ihren Jahresabschluss zu veröffentlichen", "Pflicht zu werben", "Pflicht für den Chef, im Fernsehen zu sein", "Meldepflicht bei der Polizei"], "answer": 0 }
      ]
    },
    {
      "title": "Ergonomie und Barrierefreiheit",
      "id": "ergonomie",
      "description": "Arbeitsplatzgestaltung, Beleuchtung und Entsorgung.",
      "priority": "mittel",
      "questions": [
        { "question": "Wie sollte der Monitor am Arbeitsplatz idealerweise stehen?", "options": ["Parallel zum Fenster (Blickrichtung parallel zum Fenster)", "Mit dem Rücken zum Fenster", "Direkt vor dem Fenster", "Ganz egal"], "answer": 0 },
        { "question": "Welcher Sehabstand zum Monitor wird bei 24 Zoll empfohlen?", "options": ["Ca. 50-80 cm", "Mindestens 2 Meter", "Direkt davor (10 cm)", "Gibt keine Regel"], "answer": 0 },
        { "question": "Was ist das Ziel der 'Ergonomie'?", "options": ["Optimale Anpassung der Arbeitsbedingungen an den Menschen", "Möglichst billige Büromöbel", "Möglichst bunte Büros", "Schnelles Arbeiten um jeden Preis"], "answer": 0 },
        { "question": "Wie hoch sollte ein Standard-Schreibtisch sein (idR)?", "options": ["Ca. 72-76 cm (einstellbar)", "Genau 1 Meter", "50 cm", "Egal, man kann stehen"], "answer": 0 },
        { "question": "Was bedeutet 'dynamisches Sitzen'?", "options": ["Häufiges Wechseln der Sitzposition zur Entlastung", "Sitzen auf einem Gymnastikball (nur)", "Sehr schnelles Hinsetzen", "Sitzen während man Sport macht"], "answer": 0 },
        { "question": "Was ist eine 'indirekte Beleuchtung'?", "options": ["Licht, das über Decken/Wände reflektiert wird (blendfrei)", "Eine Lampe im Schrank", "Licht das von unten kommt", "Kerzenschein"], "answer": 0 },
        { "question": "Wofür steht das 'ElektroG'?", "options": ["Elektro- und Elektronikgerätegesetz (Regelt Entsorgung)", "Elektrizitäts-Grundverordnung", "Elektronisches Geldgesetz", "Einfaches Leitungs-Gesetz"], "answer": 0 },
        { "question": "Welches Siegel kennzeichnet besonders umweltfreundliche IT-Produkte?", "options": ["Blauer Engel", "Roter Punkt", "Gelber Sack", "Grünes Kreuz"], "answer": 0 },
        { "question": "Was ist 'Barrierefreiheit' im Web (WCAG)?", "options": ["Zugänglichkeit für Menschen mit Einschränkungen (z.B. Screenreader)", "Kostenloses Internet für alle", "Webseiten ohne Passwörter", "Webseiten ohne Werbung"], "answer": 0 },
        { "question": "Was ist eine 'Lärmbelastung' am Büroarbeitsplatz (Richtwert)?", "options": ["Maximal 55 dB(A) für geistige Arbeit", "Egal solange man Musik hört", "100 dB(A)", "Stille wie im Weltraum"], "answer": 0 },
        { "question": "Was ist der Vorteil eines höhenverstellbaren Schreibtischs?", "options": ["Wechsel zwischen Sitzen und Stehen (Entlastung Rücken)", "Man kann ihn besser putzen", "Er sieht schöner aus", "Er ist teurer"], "answer": 0 },
        { "question": "Was bewirkt ein Blaulichtfilter am Monitor?", "options": ["Schonung der Augen und besserer Schlaf", "Das Bild wird schärfer", "Der PC braucht weniger Strom", "Gar nichts"], "answer": 0 },
        { "question": "Was ist eine 'Blickfeld-Ergonomie'?", "options": ["Anordnung der Arbeitsmittel im natürlichen Sichtbereich", "Die Farbe der Wand hinter dem Monitor", "Eine VR-Brille", "Ein sauberer Monitor"], "answer": 0 },
        { "question": "Was ist 'Software-Ergonomie'?", "options": ["Benutzerfreundlichkeit und intuitive Bedienung von Programmen", "Die Farbe der CD-Hülle", "Das Gewicht der Software", "Die Geschwindigkeit der CPU"], "answer": 0 },
        { "question": "Was ist 'Zwei-Sinne-Prinzip' bei Barrierefreiheit?", "options": ["Informationen müssen über mindestens zwei Sinne wahrnehmbar sein", "Man braucht zwei Augen", "Hören und Riechen", "Dasselbe wie Stereo"], "answer": 0 },
        { "question": "Warum ist Lüften im Büro wichtig (Ergonomie)?", "options": ["Zufuhr von Sauerstoff und Regulierung der Luftfeuchtigkeit", "Damit die Blätter fliegen", "Um die Kollegen zu ärgern", "Um Heizkosten zu sparen"], "answer": 0 },
        { "question": "Was ist ein 'Fußfreiraum' am Schreibtisch?", "options": ["Genügend Platz unter dem Tisch für die Beine", "Ein freier Teppich", "Socken ausziehen", "Ein Fach für Schuhe"], "answer": 0 },
        { "question": "Welche Farbe hat der 'Blaue Engel'?", "options": ["Blau und Weiß", "Grün", "Gelb", "Regenbogen"], "answer": 0 },
        { "question": "Wo entsorgt man alte Server fachgerecht?", "options": ["Wertstoffhof / spezialisierte Entsorger (ElektroG)", "Hausmüll", "Im Wald", "Einfach stehen lassen"], "answer": 0 },
        { "question": "Was ist 'Ressourceneffizienz'?", "options": ["Sparsamer Umgang mit Energie und Material", "Möglichst viel kaufen", "Alte Hardware wegwerfen", "Billige Hardware kaufen"], "answer": 0 }
      ]
    }
  ]
});
